import express from'express';import helmet from'helmet';import cookieParser from'cookie-parser';import cors from'cors';import{randomBytes,randomUUID}from'node:crypto';import{q,ready}from'./db.mjs';import{decryptJson,encryptJson,passwordRecord,tokenHash,verifyPassword,sha256}from'./crypto.mjs';

const app=express(),PORT=Number(process.env.PORT||8080),SESSION_HOURS=Number(process.env.SESSION_HOURS||12),COOKIE='kp_session';
app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'3mb'}));app.use(cookieParser());
const allowed=(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);
if(allowed.length)app.use(cors({origin:(o,cb)=>!o||allowed.includes(o)?cb(null,true):cb(new Error('origin_denied')),credentials:true}));
app.use((req,res,next)=>{if(['POST','PUT','PATCH','DELETE'].includes(req.method)){const o=req.get('origin');if(o&&allowed.length&&!allowed.includes(o))return res.status(403).json({error:'origin_denied'})}next()});

const loginAttempts=new Map();
function audit(actorId,action,detail={},caseId=null,domain=null){return q('insert into audit_events(case_id,actor_id,domain,action,detail) values($1,$2,$3,$4,$5)',[caseId,actorId,domain,action,detail])}
async function bootstrapAdmin(){
 const email=(process.env.BOOTSTRAP_ADMIN_EMAIL||'').trim().toLowerCase(),password=process.env.BOOTSTRAP_ADMIN_PASSWORD||'';if(!email||!password)return;
 const n=await q('select count(*)::int n from users');if(n.rows[0].n>0)return;const r=passwordRecord(password);
 await q('insert into users(email,display_name,password_salt,password_hash,role) values($1,$2,$3,$4,$5)',[email,'System Admin',r.salt,r.hash,'admin']);console.log('bootstrap admin created',email)
}
async function userFromReq(req){
 const tok=req.cookies?.[COOKIE];if(!tok)return null;const h=tokenHash(tok);
 const r=await q(`select u.id,u.email,u.display_name,u.role,u.active from sessions s join users u on u.id=s.user_id where s.token_hash=$1 and s.expires_at>now() and u.active=true`,[h]);return r.rows[0]||null
}
const auth=(roles=[])=>async(req,res,next)=>{const u=await userFromReq(req);if(!u)return res.status(401).json({error:'unauthorized'});if(roles.length&&!roles.includes(u.role))return res.status(403).json({error:'forbidden'});req.user=u;next()};
const cleanCase=(row)=>({...row,transcript:decryptJson(row.transcript_iv,row.transcript_cipher),transcript_iv:undefined,transcript_cipher:undefined,stt:row.stt_json,qc:row.qc_json,reviews:row.reviews||[],aiInsight:row.ai_insight||undefined,personName:row.person_name,sourceName:row.source_name,audioSha256:row.audio_sha256,durationSeconds:Number(row.duration_seconds),createdAt:row.created_at,updatedAt:row.updated_at});
const caseSelect=`select c.*,coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'decision',r.decision,'workflowScore',r.workflow_score,'conversationScore',r.conversation_score,'finalScore',r.final_score,'note',r.note,'workflowEvidence',r.workflow_evidence,'createdAt',r.created_at) order by r.created_at) from reviews r where r.case_id=c.id),'[]'::jsonb) reviews,(select jsonb_build_object('model',a.model,'summary',convert_from(decode('', 'base64'),'UTF8')) from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_placeholder from cases c`;

app.get('/api/health',async(_req,res)=>{try{res.json({ok:await ready(),service:'kuleposhti-team-api',version:'1.0.0',time:new Date().toISOString()})}catch(e){res.status(503).json({ok:false,error:'db_unavailable'})}});
app.post('/api/auth/login',async(req,res)=>{
 const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||''),key=(req.ip||'')+'|'+email,now=Date.now(),state=loginAttempts.get(key)||{n:0,until:0};if(state.until>now)return res.status(429).json({error:'temporarily_locked'});
 const r=await q('select * from users where email=$1 and active=true',[email]),u=r.rows[0];if(!u||!verifyPassword(password,u.password_salt,u.password_hash)){state.n++;if(state.n>=5){state.until=now+15*60_000;state.n=0}loginAttempts.set(key,state);return res.status(401).json({error:'invalid_credentials'})}
 loginAttempts.delete(key);const token=randomBytes(32).toString('base64url'),expires=new Date(Date.now()+SESSION_HOURS*3600_000);await q('delete from sessions where expires_at<=now()');await q('insert into sessions(user_id,token_hash,expires_at) values($1,$2,$3)',[u.id,tokenHash(token),expires]);res.cookie(COOKIE,token,{httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE!=='false',maxAge:SESSION_HOURS*3600_000,path:'/'});await audit(u.id,'login',{email});res.json({user:{id:u.id,email:u.email,displayName:u.display_name,role:u.role}})
});
app.post('/api/auth/logout',auth(),async(req,res)=>{const tok=req.cookies?.[COOKIE];if(tok)await q('delete from sessions where token_hash=$1',[tokenHash(tok)]);res.clearCookie(COOKIE,{path:'/'});await audit(req.user.id,'logout');res.json({ok:true})});
app.get('/api/auth/me',auth(),(req,res)=>res.json({user:{id:req.user.id,email:req.user.email,displayName:req.user.display_name,role:req.user.role}}));

app.get('/api/cases',auth(),async(req,res)=>{const domain=req.query.domain?String(req.query.domain):null;const r=await q(`select c.*,coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'decision',r.decision,'workflowScore',r.workflow_score,'conversationScore',r.conversation_score,'finalScore',r.final_score,'note',r.note,'workflowEvidence',r.workflow_evidence,'createdAt',r.created_at) order by r.created_at) from reviews r where r.case_id=c.id),'[]'::jsonb) reviews from cases c where c.deleted_at is null and ($1::text is null or c.domain=$1) order by c.created_at desc limit 5000`,[domain]);res.json({cases:r.rows.map(cleanCase)})});
app.get('/api/cases/hash/:hash',auth(),async(req,res)=>{const r=await q('select id from cases where audio_sha256=$1',[req.params.hash]);res.json({exists:Boolean(r.rowCount),id:r.rows[0]?.id||null})});
app.get('/api/cases/:id',auth(),async(req,res)=>{const r=await q(`select c.*,coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'decision',r.decision,'workflowScore',r.workflow_score,'conversationScore',r.conversation_score,'finalScore',r.final_score,'note',r.note,'workflowEvidence',r.workflow_evidence,'createdAt',r.created_at) order by r.created_at) from reviews r where r.case_id=c.id),'[]'::jsonb) reviews from cases c where c.id=$1 and c.deleted_at is null`,[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json({case:cleanCase(r.rows[0])})});
app.post('/api/cases',auth(),async(req,res)=>{
 const c=req.body?.case;if(!c?.id||!['sampler','physician'].includes(c.domain)||!c.personName||!c.audioSha256||!c.transcript)return res.status(400).json({error:'invalid_case'});
 const tr=encryptJson(c.transcript);try{await q(`insert into cases(id,domain,person_name,source_name,audio_sha256,duration_seconds,transcript_iv,transcript_cipher,stt_json,qc_json,status,created_by,updated_by,created_at,updated_at)
 values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12,$13,$14)
 on conflict(id) do update set person_name=excluded.person_name,source_name=excluded.source_name,duration_seconds=excluded.duration_seconds,transcript_iv=excluded.transcript_iv,transcript_cipher=excluded.transcript_cipher,stt_json=excluded.stt_json,qc_json=excluded.qc_json,status=excluded.status,updated_by=excluded.updated_by,updated_at=excluded.updated_at`,
 [c.id,c.domain,c.personName,c.sourceName||'',c.audioSha256,Number(c.durationSeconds||0),tr.iv,tr.cipher,c.stt||{},c.qc||{},c.status||'needs_review',req.user.id,c.createdAt||new Date().toISOString(),c.updatedAt||new Date().toISOString()]);await audit(req.user.id,'case_upsert',{status:c.status,sourceName:c.sourceName},c.id,c.domain);res.status(201).json({ok:true,id:c.id})}catch(e){if(String(e?.code)==='23505')return res.status(409).json({error:'duplicate_audio'});throw e}
});
app.delete('/api/cases/:id',auth(['supervisor','admin']),async(req,res)=>{const r=await q('select domain,source_name,person_name from cases where id=$1 and deleted_at is null',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req.user.id,'case_deleted',{sourceName:r.rows[0].source_name,personName:r.rows[0].person_name},req.params.id,r.rows[0].domain);await q('update cases set deleted_at=now(),updated_by=$2,updated_at=now() where id=$1',[req.params.id,req.user.id]);res.json({ok:true})});
app.post('/api/cases/:id/reviews',auth(['reviewer','supervisor','admin']),async(req,res)=>{
 const{decision,workflowScore,conversationScore,finalScore,note,workflowEvidence}=req.body||{};if(!['approved','referred','overridden','rejected'].includes(decision)||!String(note||'').trim())return res.status(400).json({error:'invalid_review'});
 const c=await q('select domain from cases where id=$1',[req.params.id]);if(!c.rowCount)return res.status(404).json({error:'not_found'});const id=randomUUID(),at=new Date().toISOString();
 await q('insert into reviews(id,case_id,decision,workflow_score,conversation_score,final_score,note,workflow_evidence,reviewer_id,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,req.params.id,decision,workflowScore,conversationScore,finalScore,String(note).trim(),workflowEvidence||null,req.user.id,at]);await q(`update cases set status=$1,updated_by=$2,updated_at=$3,qc_json=qc_json || jsonb_build_object('workflowScore',$5::numeric,'finalScore',$6::numeric,'workflowEvidence',$7::jsonb) where id=$4`,[decision==='referred'?'needs_review':'completed',req.user.id,at,req.params.id,workflowScore,finalScore,JSON.stringify(workflowEvidence||null)]);await audit(req.user.id,'review_submitted',{decision,workflowScore,finalScore,note},req.params.id,c.rows[0].domain);res.status(201).json({ok:true,id})
});
app.post('/api/cases/:id/ai-insight',auth(),async(req,res)=>{const model=String(req.body?.model||'local'),summary=String(req.body?.summary||'').trim();if(!summary)return res.status(400).json({error:'summary_required'});const c=await q('select domain from cases where id=$1',[req.params.id]);if(!c.rowCount)return res.status(404).json({error:'not_found'});const enc=encryptJson(summary);await q('insert into ai_insights(case_id,model,summary_iv,summary_cipher,payload,created_by) values($1,$2,$3,$4,$5,$6)',[req.params.id,model,enc.iv,enc.cipher,req.body?.payload||{},req.user.id]);await audit(req.user.id,'local_ai_insight',{model},req.params.id,c.rows[0].domain);res.status(201).json({ok:true})});
app.get('/api/audit',auth(['reviewer','supervisor','admin']),async(req,res)=>{const r=await q('select id,case_id,domain,action,detail,created_at from audit_events order by created_at desc limit 2000');res.json({audit:r.rows.map(x=>({id:x.id,caseId:x.case_id,domain:x.domain,action:x.action,detail:x.detail,createdAt:x.created_at}))})});

app.get('/api/users',auth(['admin']),async(_req,res)=>{const r=await q('select id,email,display_name as "displayName",role,active,created_at as "createdAt" from users order by created_at');res.json({users:r.rows})});
app.post('/api/users',auth(['admin']),async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase(),display=String(req.body?.displayName||'').trim(),role=String(req.body?.role||''),password=String(req.body?.password||'');if(!email||!display||!['operator','reviewer','supervisor','admin'].includes(role))return res.status(400).json({error:'invalid_user'});const pr=passwordRecord(password);const r=await q('insert into users(email,display_name,password_salt,password_hash,role) values($1,$2,$3,$4,$5) returning id,email,display_name as "displayName",role,active',[email,display,pr.salt,pr.hash,role]);await audit(req.user.id,'user_created',{email,role});res.status(201).json({user:r.rows[0]})});
app.patch('/api/users/:id',auth(['admin']),async(req,res)=>{const active=Boolean(req.body?.active),role=req.body?.role;if(role&&!['operator','reviewer','supervisor','admin'].includes(role))return res.status(400).json({error:'invalid_role'});await q('update users set active=$1,role=coalesce($2,role) where id=$3',[active,role||null,req.params.id]);await audit(req.user.id,'user_updated',{target:req.params.id,active,role});res.json({ok:true})});

app.get('/api/rule-packs',auth(),async(req,res)=>{const r=await q('select id,domain,version,status,sha256,content_json as content,created_at as "createdAt" from rule_packs order by created_at desc');res.json({rulePacks:r.rows})});
app.post('/api/rule-packs',auth(['supervisor','admin']),async(req,res)=>{const{domain,version,status='candidate',content}=req.body||{};if(!['sampler','physician'].includes(domain)||!version||!content)return res.status(400).json({error:'invalid_rule_pack'});const hash=sha256(JSON.stringify(content));await q('insert into rule_packs(domain,version,status,sha256,content_json,created_by) values($1,$2,$3,$4,$5,$6)',[domain,version,status,hash,content,req.user.id]);await audit(req.user.id,'rule_pack_created',{domain,version,status,sha256:hash},null,domain);res.status(201).json({ok:true,sha256:hash})});

app.use((err,req,res,_next)=>{console.error(err);res.status(500).json({error:'internal_error',requestId:req.get('x-request-id')||null})});
await bootstrapAdmin();app.listen(PORT,'0.0.0.0',()=>console.log('KulePoshti team API listening',PORT));
