import express from'express';import helmet from'helmet';import cookieParser from'cookie-parser';import cors from'cors';import multer from'multer';import{randomBytes,randomUUID}from'node:crypto';import{q,ready}from'./db.mjs';import{decryptJson,encryptJson,passwordRecord,tokenHash,verifyPassword,sha256}from'./crypto.mjs';import{writeEncryptedAudio}from'./audio-spool.mjs';import{oganesonHealth,OGANESON_CONTRACT}from'./oganeson.mjs';import{analyzeText}from'./text-core.mjs';import{persistTranscriptCase,subjectHistory}from'./case-service.mjs';

const app=express(),PORT=Number(process.env.PORT||8080),SESSION_HOURS=Number(process.env.SESSION_HOURS||12),COOKIE='kp_session',MAX_AUDIO_MB=Number(process.env.MAX_AUDIO_MB||40);const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:MAX_AUDIO_MB*1024*1024,files:1}});
app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'3mb'}));app.use(cookieParser());
const allowed=(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);
if(allowed.length)app.use(cors({origin:(o,cb)=>!o||allowed.includes(o)?cb(null,true):cb(new Error('origin_denied')),credentials:true}));
app.use((req,res,next)=>{if(['POST','PUT','PATCH','DELETE'].includes(req.method)){const o=req.get('origin');if(o&&allowed.length&&!allowed.includes(o))return res.status(403).json({error:'origin_denied'})}next()});

const loginAttempts=new Map();
function audit(actorId,action,detail={},caseId=null,domain=null){return q('insert into audit_events(case_id,actor_id,domain,action,detail) values($1,$2,$3,$4,$5)',[caseId,actorId,domain,action,detail])}
async function bootstrapAdmin(){
 const email=(process.env.BOOTSTRAP_ADMIN_EMAIL||'').trim().toLowerCase(),password=process.env.BOOTSTRAP_ADMIN_PASSWORD||'';if(!email||!password)return;
 const n=await q('select count(*)::int n from users');if(n.rows[0].n>0)return;const r=passwordRecord(password);
 await q('insert into users(email,display_name,password_salt,password_hash,role) values($1,$2,$3,$4,$5)',[email,'System Admin',r.salt,r.hash,'admin']);console.log('bootstrap admin created',email)
}
async function userFromReq(req){
 const tok=req.cookies?.[COOKIE];if(!tok)return null;const h=tokenHash(tok);
 const r=await q(`select u.id,u.email,u.display_name,u.role,u.active from sessions s join users u on u.id=s.user_id where s.token_hash=$1 and s.expires_at>now() and u.active=true`,[h]);return r.rows[0]||null
}
const auth=(roles=[])=>async(req,res,next)=>{const u=await userFromReq(req);if(!u)return res.status(401).json({error:'unauthorized'});if(roles.length&&!roles.includes(u.role))return res.status(403).json({error:'forbidden'});req.user=u;next()};
const cleanCase=(row)=>({...row,transcript:decryptJson(row.transcript_iv,row.transcript_cipher),transcript_iv:undefined,transcript_cipher:undefined,stt:row.stt_json,qc:row.qc_json,nlp:row.nlp_json||{},reviews:row.reviews||[],aiInsight:row.ai_summary_iv?{model:row.ai_model,summary:decryptJson(row.ai_summary_iv,row.ai_summary_cipher),createdAt:row.ai_created_at}:undefined,personName:row.person_name,sourceName:row.source_name,audioSha256:row.audio_sha256,durationSeconds:Number(row.duration_seconds),occurredAt:row.occurred_at?String(row.occurred_at).slice(0,10):undefined,personMeta:row.person_meta||{},subjectKey:row.subject_key||null,sourceSystem:row.source_system||null,sourceRef:row.source_ref||null,createdAt:row.created_at,updatedAt:row.updated_at});
app.get('/api/health',async(_req,res)=>{try{res.json({ok:await ready(),service:'kuleposhti-team-api',version:'3.0.0-candidate',textCore:'3.0.0',oganeson:OGANESON_CONTRACT,time:new Date().toISOString()})}catch(e){res.status(503).json({ok:false,error:'db_unavailable'})}});
app.get('/api/oganeson/health',auth(),async(_req,res)=>{const h=await oganesonHealth();res.status(h.ok?200:503).json(h)});
app.post('/api/auth/login',async(req,res)=>{
 const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||''),key=(req.ip||'')+'|'+email,now=Date.now(),state=loginAttempts.get(key)||{n:0,until:0};if(state.until>now)return res.status(429).json({error:'temporarily_locked'});
 const r=await q('select * from users where email=$1 and active=true',[email]),u=r.rows[0];if(!u||!verifyPassword(password,u.password_salt,u.password_hash)){state.n++;if(state.n>=5){state.until=now+15*60_000;state.n=0}loginAttempts.set(key,state);return res.status(401).json({error:'invalid_credentials'})}
 loginAttempts.delete(key);const token=randomBytes(32).toString('base64url'),expires=new Date(Date.now()+SESSION_HOURS*3600_000);await q('delete from sessions where expires_at<=now()');await q('insert into sessions(user_id,token_hash,expires_at) values($1,$2,$3)',[u.id,tokenHash(token),expires]);res.cookie(COOKIE,token,{httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE!=='false',maxAge:SESSION_HOURS*3600_000,path:'/'});await audit(u.id,'login',{email});res.json({user:{id:u.id,email:u.email,displayName:u.display_name,role:u.role}})
});
app.post('/api/auth/logout',auth(),async(req,res)=>{const tok=req.cookies?.[COOKIE];if(tok)await q('delete from sessions where token_hash=$1',[tokenHash(tok)]);res.clearCookie(COOKIE,{path:'/'});await audit(req.user.id,'logout');res.json({ok:true})});
app.get('/api/auth/session',async(req,res)=>{const u=await userFromReq(req);res.json({user:u?{id:u.id,email:u.email,displayName:u.display_name,role:u.role}:null})});
app.get('/api/auth/me',auth(),(req,res)=>res.json({user:{id:req.user.id,email:req.user.email,displayName:req.user.display_name,role:req.user.role}}));

app.post('/api/text/analyze',auth(),async(req,res)=>{
 const{domain,text,segments=[],durationSeconds=0,workflow={},userKey=null}=req.body||{};
 if(!['physician','sampler','voc'].includes(domain)||typeof text!=='string')return res.status(400).json({error:'invalid_text_analysis_request'});
 try{res.json({analysis:analyzeText(domain,text,{segments,durationSeconds,workflow,userKey})})}catch(e){res.status(422).json({error:String(e?.message||e)})}
});
app.post('/api/ingest/transcript',auth(),async(req,res)=>{
 const b=req.body||{};
 try{
  const out=await persistTranscriptCase({domain:b.domain,subjectName:b.subjectName,subjectKey:b.subjectKey,transcript:b.transcript,segments:b.segments||[],durationSeconds:Number(b.durationSeconds||0),audioSha256:b.audioSha256||null,sourceName:b.sourceName||'transcript',sourceSystem:b.sourceSystem||'oganeson',sourceRef:b.sourceRef||null,workflow:b.workflow||{},occurredAt:b.occurredAt||null,personMeta:b.personMeta||{},actorId:req.user.id});
  res.status(201).json({ok:true,...out})
 }catch(e){if(String(e?.code)==='23505')return res.status(409).json({error:'duplicate_interaction'});res.status(422).json({error:String(e?.message||e)})}
});
app.post('/api/stt/jobs',auth(),upload.single('file'),async(req,res)=>{
 const file=req.file;if(!file)return res.status(400).json({error:'audio_required'});
 const domain=String(req.body?.domain||''),subjectName=String(req.body?.subjectName||'').trim(),subjectKey=String(req.body?.subjectKey||'').trim()||null;
 if(!['physician','sampler','voc'].includes(domain)||!subjectName)return res.status(400).json({error:'invalid_job_metadata'});
 const audioHash=sha256(file.buffer),dup=await q("select id from cases where audio_sha256=$1 and deleted_at is null",[audioHash]);
 if(dup.rowCount)return res.status(409).json({error:'duplicate_audio',caseId:dup.rows[0].id});
 const active=await q("select id from transcription_jobs where audio_sha256=$1 and status in('queued','running','completed') order by created_at desc limit 1",[audioHash]);
 if(active.rowCount)return res.status(409).json({error:'duplicate_job',jobId:active.rows[0].id});
 const id=randomUUID(),spool=await writeEncryptedAudio(id,file.buffer);
 let workflow={};try{workflow=req.body?.workflow?JSON.parse(req.body.workflow):{}}catch{return res.status(400).json({error:'invalid_workflow_json'})}
 const occurredAt=String(req.body?.occurredAt||'').trim()||null,sourceSystem=String(req.body?.sourceSystem||'operator_upload'),sourceRef=String(req.body?.sourceRef||'').trim()||null;
 await q("insert into transcription_jobs(id,domain,subject_key,subject_name,source_name,source_system,source_ref,audio_sha256,audio_bytes,mime_type,spool_path,workflow_json,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)",[id,domain,subjectKey,subjectName,file.originalname||'audio.wav',sourceSystem,sourceRef,audioHash,file.size,file.mimetype||'audio/wav',spool,{workflow,occurredAt,personMeta:{},subjectMeta:{}},req.user.id]);
 await audit(req.user.id,'transcription_job_created',{jobId:id,sourceName:file.originalname,audioBytes:file.size},null,domain);
 res.status(202).json({ok:true,job:{id,status:'queued',domain,subjectName,audioSha256:audioHash}})
});
app.get('/api/stt/jobs',auth(),async(req,res)=>{const r=await q(`select id,domain,subject_key as "subjectKey",subject_name as "subjectName",source_name as "sourceName",audio_sha256 as "audioSha256",audio_bytes as "audioBytes",status,attempts,max_attempts as "maxAttempts",provider_json as "provider",result_case_id as "resultCaseId",last_error as "lastError",created_at as "createdAt",started_at as "startedAt",completed_at as "completedAt" from transcription_jobs order by created_at desc limit 1000`);res.json({jobs:r.rows})});
app.get('/api/stt/jobs/:id',auth(),async(req,res)=>{const r=await q(`select id,domain,subject_key as "subjectKey",subject_name as "subjectName",source_name as "sourceName",audio_sha256 as "audioSha256",audio_bytes as "audioBytes",status,attempts,max_attempts as "maxAttempts",provider_json as "provider",result_case_id as "resultCaseId",last_error as "lastError",created_at as "createdAt",started_at as "startedAt",completed_at as "completedAt" from transcription_jobs where id=$1`,[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json({job:r.rows[0]})});
app.post('/api/stt/jobs/:id/retry',auth(['reviewer','supervisor','admin']),async(req,res)=>{const r=await q("update transcription_jobs set status='queued',last_error=null,updated_at=now() where id=$1 and status in('failed','dead_letter') returning id",[req.params.id]);if(!r.rowCount)return res.status(409).json({error:'job_not_retryable'});await audit(req.user.id,'transcription_job_retried',{jobId:req.params.id});res.json({ok:true})});
app.get('/api/profiles/:domain/:key',auth(),async(req,res)=>{const domain=String(req.params.domain),key=decodeURIComponent(req.params.key);if(!['physician','sampler','voc'].includes(domain))return res.status(400).json({error:'invalid_domain'});const out=await subjectHistory({domain,subjectKey:key,from:req.query.from||null,to:req.query.to||null,limit:req.query.limit||1000});if(!out)return res.status(404).json({error:'not_found'});res.json(out)});


app.get('/api/cases',auth(),async(req,res)=>{const domain=req.query.domain?String(req.query.domain):null;const r=await q(`select c.*,coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'decision',r.decision,'workflowScore',r.workflow_score,'conversationScore',r.conversation_score,'finalScore',r.final_score,'note',r.note,'workflowEvidence',r.workflow_evidence,'createdAt',r.created_at) order by r.created_at) from reviews r where r.case_id=c.id),'[]'::jsonb) reviews,(select a.model from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_model,(select a.summary_iv from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_summary_iv,(select a.summary_cipher from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_summary_cipher,(select a.created_at from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_created_at from cases c where c.deleted_at is null and ($1::text is null or c.domain=$1) order by c.created_at desc limit 5000`,[domain]);res.json({cases:r.rows.map(cleanCase)})});
app.get('/api/cases/hash/:hash',auth(),async(req,res)=>{const r=await q('select id from cases where audio_sha256=$1',[req.params.hash]);res.json({exists:Boolean(r.rowCount),id:r.rows[0]?.id||null})});
app.get('/api/cases/:id',auth(),async(req,res)=>{const r=await q(`select c.*,coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'decision',r.decision,'workflowScore',r.workflow_score,'conversationScore',r.conversation_score,'finalScore',r.final_score,'note',r.note,'workflowEvidence',r.workflow_evidence,'createdAt',r.created_at) order by r.created_at) from reviews r where r.case_id=c.id),'[]'::jsonb) reviews,(select a.model from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_model,(select a.summary_iv from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_summary_iv,(select a.summary_cipher from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_summary_cipher,(select a.created_at from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_created_at from cases c where c.id=$1 and c.deleted_at is null`,[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json({case:cleanCase(r.rows[0])})});
app.post('/api/cases',auth(),async(req,res)=>{
 const c=req.body?.case;if(!c?.id||!['sampler','physician','voc'].includes(c.domain)||!c.personName||!c.audioSha256||!c.transcript)return res.status(400).json({error:'invalid_case'});
 const tr=encryptJson(c.transcript);try{await q(`insert into cases(id,domain,person_name,source_name,audio_sha256,duration_seconds,transcript_iv,transcript_cipher,stt_json,qc_json,status,created_by,updated_by,created_at,updated_at,occurred_at,person_meta)
 values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12,$13,$14,$15,$16)
 on conflict(id) do update set person_name=excluded.person_name,source_name=excluded.source_name,duration_seconds=excluded.duration_seconds,transcript_iv=excluded.transcript_iv,transcript_cipher=excluded.transcript_cipher,stt_json=excluded.stt_json,qc_json=excluded.qc_json,status=excluded.status,updated_by=excluded.updated_by,updated_at=excluded.updated_at,occurred_at=excluded.occurred_at,person_meta=excluded.person_meta`,
 [c.id,c.domain,c.personName,c.sourceName||'',c.audioSha256,Number(c.durationSeconds||0),tr.iv,tr.cipher,c.stt||{},c.qc||{},c.status||'needs_review',req.user.id,c.createdAt||new Date().toISOString(),c.updatedAt||new Date().toISOString(),c.occurredAt||null,c.personMeta||{}]);await audit(req.user.id,'case_upsert',{status:c.status,sourceName:c.sourceName},c.id,c.domain);res.status(201).json({ok:true,id:c.id})}catch(e){if(String(e?.code)==='23505')return res.status(409).json({error:'duplicate_audio'});throw e}
});
app.delete('/api/cases/:id',auth(['supervisor','admin']),async(req,res)=>{const r=await q('select domain,source_name,person_name from cases where id=$1 and deleted_at is null',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req.user.id,'case_deleted',{sourceName:r.rows[0].source_name,personName:r.rows[0].person_name},req.params.id,r.rows[0].domain);await q('update cases set deleted_at=now(),updated_by=$2,updated_at=now() where id=$1',[req.params.id,req.user.id]);res.json({ok:true})});
app.post('/api/cases/:id/reviews',auth(['reviewer','supervisor','admin']),async(req,res)=>{
 const{decision,workflowScore,conversationScore,finalScore,note,workflowEvidence}=req.body||{};if(!['approved','referred','overridden','rejected'].includes(decision)||!String(note||'').trim())return res.status(400).json({error:'invalid_review'});
 const c=await q('select domain from cases where id=$1',[req.params.id]);if(!c.rowCount)return res.status(404).json({error:'not_found'});const id=randomUUID(),at=new Date().toISOString();
 await q('insert into reviews(id,case_id,decision,workflow_score,conversation_score,final_score,note,workflow_evidence,reviewer_id,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,req.params.id,decision,workflowScore,conversationScore,finalScore,String(note).trim(),workflowEvidence||null,req.user.id,at]);await q(`update cases set status=$1,updated_by=$2,updated_at=$3,qc_json=qc_json || jsonb_build_object('workflowScore',$5::numeric,'finalScore',$6::numeric,'workflowEvidence',$7::jsonb) where id=$4`,[decision==='referred'?'needs_review':'completed',req.user.id,at,req.params.id,workflowScore,finalScore,JSON.stringify(workflowEvidence||null)]);await audit(req.user.id,'review_submitted',{decision,workflowScore,finalScore,note},req.params.id,c.rows[0].domain);res.status(201).json({ok:true,id})
});
app.post('/api/cases/:id/ai-insight',auth(),async(req,res)=>{const model=String(req.body?.model||'local'),summary=String(req.body?.summary||'').trim();if(!summary)return res.status(400).json({error:'summary_required'});const c=await q('select domain from cases where id=$1',[req.params.id]);if(!c.rowCount)return res.status(404).json({error:'not_found'});const enc=encryptJson(summary);await q('insert into ai_insights(case_id,model,summary_iv,summary_cipher,payload,created_by) values($1,$2,$3,$4,$5,$6)',[req.params.id,model,enc.iv,enc.cipher,req.body?.payload||{},req.user.id]);await audit(req.user.id,'local_ai_insight',{model},req.params.id,c.rows[0].domain);res.status(201).json({ok:true})});
app.get('/api/audit',auth(['reviewer','supervisor','admin']),async(req,res)=>{const r=await q('select id,case_id,domain,action,detail,created_at from audit_events order by created_at desc limit 2000');res.json({audit:r.rows.map(x=>({id:x.id,caseId:x.case_id,domain:x.domain,action:x.action,detail:x.detail,createdAt:x.created_at}))})});

app.get('/api/samplers',auth(),async(_req,res)=>{const r=await q('select id,full_name as name,grade,city,active,source,created_at as "createdAt" from samplers where active=true order by full_name');res.json({samplers:r.rows})});
app.post('/api/samplers',auth(),async(req,res)=>{const name=String(req.body?.name||'').normalize('NFKC').replace(/[يى]/g,'ی').replace(/[ك]/g,'ک').replace(/\s+/g,' ').trim(),grade=String(req.body?.grade||'').trim().toUpperCase(),city=String(req.body?.city||'').trim();if(name.length<3||!grade||!city)return res.status(400).json({error:'invalid_sampler'});try{const r=await q('insert into samplers(full_name,grade,city,source) values($1,$2,$3,$4) returning id,full_name as name,grade,city,active,source,created_at as "createdAt"',[name,grade,city,'manual']);await audit(req.user.id,'sampler_created',{name,grade,city},null,'sampler');res.status(201).json({sampler:r.rows[0]})}catch(e){if(String(e?.code)==='23505')return res.status(409).json({error:'sampler_exists'});throw e}});

app.get('/api/users',auth(['admin']),async(_req,res)=>{const r=await q('select id,email,display_name as "displayName",role,active,created_at as "createdAt" from users order by created_at');res.json({users:r.rows})});
app.post('/api/users',auth(['admin']),async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase(),display=String(req.body?.displayName||'').trim(),role=String(req.body?.role||''),password=String(req.body?.password||'');if(!email||!display||!['operator','reviewer','supervisor','admin'].includes(role))return res.status(400).json({error:'invalid_user'});const pr=passwordRecord(password);const r=await q('insert into users(email,display_name,password_salt,password_hash,role) values($1,$2,$3,$4,$5) returning id,email,display_name as "displayName",role,active',[email,display,pr.salt,pr.hash,role]);await audit(req.user.id,'user_created',{email,role});res.status(201).json({user:r.rows[0]})});
app.patch('/api/users/:id',auth(['admin']),async(req,res)=>{const active=Boolean(req.body?.active),role=req.body?.role;if(role&&!['operator','reviewer','supervisor','admin'].includes(role))return res.status(400).json({error:'invalid_role'});await q('update users set active=$1,role=coalesce($2,role) where id=$3',[active,role||null,req.params.id]);await audit(req.user.id,'user_updated',{target:req.params.id,active,role});res.json({ok:true})});

app.get('/api/rule-packs',auth(),async(req,res)=>{const r=await q('select id,domain,version,status,sha256,content_json as content,created_at as "createdAt" from rule_packs order by created_at desc');res.json({rulePacks:r.rows})});
app.post('/api/rule-packs',auth(['supervisor','admin']),async(req,res)=>{const{domain,version,status='candidate',content}=req.body||{};if(!['sampler','physician','voc'].includes(domain)||!version||!content)return res.status(400).json({error:'invalid_rule_pack'});const hash=sha256(JSON.stringify(content));await q('insert into rule_packs(domain,version,status,sha256,content_json,created_by) values($1,$2,$3,$4,$5,$6)',[domain,version,status,hash,content,req.user.id]);await audit(req.user.id,'rule_pack_created',{domain,version,status,sha256:hash},null,domain);res.status(201).json({ok:true,sha256:hash})});

app.use((err,req,res,_next)=>{console.error(err);res.status(500).json({error:'internal_error',requestId:req.get('x-request-id')||null})});
await bootstrapAdmin();app.listen(PORT,'0.0.0.0',()=>console.log('KulePoshti team API listening',PORT));
