import express from'express';import helmet from'helmet';import cookieParser from'cookie-parser';import cors from'cors';import{randomBytes,randomUUID}from'node:crypto';import{q,ready,tx}from'./db.mjs';import{decryptJson,encryptJson,passwordRecord,tokenHash,verifyPassword,sha256}from'./crypto.mjs';import{analyzeTranscript,textIntelligenceHealth}from'./textIntelligence.mjs';import{parseDateInput,dualDate}from'./calendar.mjs';

const app=express(),PORT=Number(process.env.PORT||8080),SESSION_HOURS=Number(process.env.SESSION_HOURS||12),COOKIE='kp_session',OGANSON_SECRET=String(process.env.OGANSON_SHARED_SECRET||'');
app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'3mb'}));app.use(cookieParser());
const allowed=(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);
if(allowed.length)app.use(cors({origin:(o,cb)=>!o||allowed.includes(o)?cb(null,true):cb(new Error('origin_denied')),credentials:true}));
app.use((req,res,next)=>{if(['POST','PUT','PATCH','DELETE'].includes(req.method)){const o=req.get('origin');if(o&&allowed.length&&!allowed.includes(o))return res.status(403).json({error:'origin_denied'})}next()});

const loginAttempts=new Map();
function audit(actorId,action,detail={},caseId=null,domain=null){return q('insert into audit_events(case_id,actor_id,domain,action,detail) values($1,$2,$3,$4,$5)',[caseId,actorId,domain,action,detail])}
async function bootstrapAdmin(){
 const email=(process.env.BOOTSTRAP_ADMIN_EMAIL||'').trim().toLowerCase(),password=process.env.BOOTSTRAP_ADMIN_PASSWORD||'';if(!email||!password)return;
 const n=await q('select count(*)::int n from users');if(n.rows[0].n>0)return;const r=passwordRecord(password);
 await q('insert into users(email,display_name,password_salt,password_hash,role) values($1,$2,$3,$4,$5)',[email,'System Admin',r.salt,r.hash,'admin']);console.log('bootstrap admin created',email)
}
async function userFromReq(req){
 const tok=req.cookies?.[COOKIE];if(!tok)return null;const h=tokenHash(tok);
 const r=await q(`select u.id,u.email,u.display_name,u.role,u.active from sessions s join users u on u.id=s.user_id where s.token_hash=$1 and s.expires_at>now() and u.active=true`,[h]);return r.rows[0]||null
}
const auth=(roles=[])=>async(req,res,next)=>{const u=await userFromReq(req);if(!u)return res.status(401).json({error:'unauthorized'});if(roles.length&&!roles.includes(u.role))return res.status(403).json({error:'forbidden'});req.user=u;next()};
const cleanCase=(row)=>({...row,transcript:decryptJson(row.transcript_iv,row.transcript_cipher),transcript_iv:undefined,transcript_cipher:undefined,stt:row.stt_json,qc:row.qc_json,analysis:row.transcript_analysis_json||{},reviews:row.reviews||[],aiInsight:row.ai_summary_iv?{model:row.ai_model,summary:decryptJson(row.ai_summary_iv,row.ai_summary_cipher),createdAt:row.ai_created_at}:undefined,personName:row.person_name,sourceName:row.source_name,audioSha256:row.audio_sha256,durationSeconds:Number(row.duration_seconds),occurredAt:row.occurred_at_ts||row.occurred_at||row.created_at,personMeta:row.person_meta||{},subjectId:row.subject_id,externalId:row.external_id,externalSource:row.external_source,processingVersion:row.processing_version,createdAt:row.created_at,updatedAt:row.updated_at});
app.get('/api/health',async(_req,res)=>{try{let textIntelligence=null;try{textIntelligence=await textIntelligenceHealth()}catch{textIntelligence={ok:false}}res.json({ok:await ready(),service:'kuleposhti-team-api',version:'2.0.0',textIntelligence,time:new Date().toISOString()})}catch(e){res.status(503).json({ok:false,error:'db_unavailable'})}});
app.post('/api/auth/login',async(req,res)=>{
 const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||''),key=(req.ip||'')+'|'+email,now=Date.now(),state=loginAttempts.get(key)||{n:0,until:0};if(state.until>now)return res.status(429).json({error:'temporarily_locked'});
 const r=await q('select * from users where email=$1 and active=true',[email]),u=r.rows[0];if(!u||!verifyPassword(password,u.password_salt,u.password_hash)){state.n++;if(state.n>=5){state.until=now+15*60_000;state.n=0}loginAttempts.set(key,state);return res.status(401).json({error:'invalid_credentials'})}
 loginAttempts.delete(key);const token=randomBytes(32).toString('base64url'),expires=new Date(Date.now()+SESSION_HOURS*3600_000);await q('delete from sessions where expires_at<=now()');await q('insert into sessions(user_id,token_hash,expires_at) values($1,$2,$3)',[u.id,tokenHash(token),expires]);res.cookie(COOKIE,token,{httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE!=='false',maxAge:SESSION_HOURS*3600_000,path:'/'});await audit(u.id,'login',{email});res.json({user:{id:u.id,email:u.email,displayName:u.display_name,role:u.role}})
});
app.post('/api/auth/logout',auth(),async(req,res)=>{const tok=req.cookies?.[COOKIE];if(tok)await q('delete from sessions where token_hash=$1',[tokenHash(tok)]);res.clearCookie(COOKIE,{path:'/'});await audit(req.user.id,'logout');res.json({ok:true})});
app.get('/api/auth/session',async(req,res)=>{const u=await userFromReq(req);res.json({user:u?{id:u.id,email:u.email,displayName:u.display_name,role:u.role}:null})});
app.get('/api/auth/me',auth(),(req,res)=>res.json({user:{id:req.user.id,email:req.user.email,displayName:req.user.display_name,role:req.user.role}}));

app.get('/api/cases',auth(),async(req,res)=>{
 const domain=req.query.domain?String(req.query.domain):null,person=req.query.person?String(req.query.person):null,status=req.query.status?String(req.query.status):null,calendar=String(req.query.calendar||'gregorian');
 let from=null,to=null;try{from=req.query.from?parseDateInput(String(req.query.from),calendar):null;to=req.query.to?parseDateInput(String(req.query.to),calendar):null}catch{return res.status(400).json({error:'invalid_date_filter'})}
 const r=await q(`select c.*,coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'decision',r.decision,'workflowScore',r.workflow_score,'conversationScore',r.conversation_score,'finalScore',r.final_score,'note',r.note,'workflowEvidence',r.workflow_evidence,'createdAt',r.created_at) order by r.created_at) from reviews r where r.case_id=c.id),'[]'::jsonb) reviews,(select a.model from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_model,(select a.summary_iv from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_summary_iv,(select a.summary_cipher from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_summary_cipher,(select a.created_at from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_created_at from cases c where c.deleted_at is null and ($1::text is null or c.domain=$1) and ($2::text is null or c.person_name ilike '%'||$2||'%') and ($3::text is null or c.status=$3) and ($4::date is null or coalesce(c.occurred_at_ts::date,c.occurred_at,c.created_at::date)>=$4::date) and ($5::date is null or coalesce(c.occurred_at_ts::date,c.occurred_at,c.created_at::date)<=$5::date) order by coalesce(c.occurred_at_ts,c.created_at) desc limit 5000`,[domain,person,status,from,to]);res.json({cases:r.rows.map(cleanCase),filter:{domain,person,status,from,to,calendar}})
});
app.get('/api/cases/hash/:hash',auth(),async(req,res)=>{const r=await q('select id from cases where audio_sha256=$1',[req.params.hash]);res.json({exists:Boolean(r.rowCount),id:r.rows[0]?.id||null})});
app.get('/api/cases/:id',auth(),async(req,res)=>{const r=await q(`select c.*,coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'decision',r.decision,'workflowScore',r.workflow_score,'conversationScore',r.conversation_score,'finalScore',r.final_score,'note',r.note,'workflowEvidence',r.workflow_evidence,'createdAt',r.created_at) order by r.created_at) from reviews r where r.case_id=c.id),'[]'::jsonb) reviews,(select a.model from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_model,(select a.summary_iv from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_summary_iv,(select a.summary_cipher from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_summary_cipher,(select a.created_at from ai_insights a where a.case_id=c.id order by a.created_at desc limit 1) ai_created_at from cases c where c.id=$1 and c.deleted_at is null`,[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json({case:cleanCase(r.rows[0])})});
app.post('/api/cases',auth(),async(req,res)=>{
 const c=req.body?.case;if(!c?.id||!['sampler','physician','voc'].includes(c.domain)||!c.personName||!c.audioSha256||!c.transcript)return res.status(400).json({error:'invalid_case'});
 const tr=encryptJson(c.transcript);try{await q(`insert into cases(id,domain,person_name,source_name,audio_sha256,duration_seconds,transcript_iv,transcript_cipher,stt_json,qc_json,status,created_by,updated_by,created_at,updated_at,occurred_at,person_meta)
 values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12,$13,$14,$15,$16)
 on conflict(id) do update set person_name=excluded.person_name,source_name=excluded.source_name,duration_seconds=excluded.duration_seconds,transcript_iv=excluded.transcript_iv,transcript_cipher=excluded.transcript_cipher,stt_json=excluded.stt_json,qc_json=excluded.qc_json,status=excluded.status,updated_by=excluded.updated_by,updated_at=excluded.updated_at,occurred_at=excluded.occurred_at,person_meta=excluded.person_meta`,
 [c.id,c.domain,c.personName,c.sourceName||'',c.audioSha256,Number(c.durationSeconds||0),tr.iv,tr.cipher,c.stt||{},c.qc||{},c.status||'needs_review',req.user.id,c.createdAt||new Date().toISOString(),c.updatedAt||new Date().toISOString(),c.occurredAt||null,c.personMeta||{}]);await audit(req.user.id,'case_upsert',{status:c.status,sourceName:c.sourceName},c.id,c.domain);res.status(201).json({ok:true,id:c.id})}catch(e){if(String(e?.code)==='23505')return res.status(409).json({error:'duplicate_audio'});throw e}
});
app.delete('/api/cases/:id',auth(['supervisor','admin']),async(req,res)=>{const r=await q('select domain,source_name,person_name from cases where id=$1 and deleted_at is null',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'not_found'});await audit(req.user.id,'case_deleted',{sourceName:r.rows[0].source_name,personName:r.rows[0].person_name},req.params.id,r.rows[0].domain);await q('update cases set deleted_at=now(),updated_by=$2,updated_at=now() where id=$1',[req.params.id,req.user.id]);res.json({ok:true})});
app.post('/api/cases/:id/reviews',auth(['reviewer','supervisor','admin']),async(req,res)=>{
 const{decision,workflowScore,conversationScore,finalScore,note,workflowEvidence}=req.body||{};if(!['approved','referred','overridden','rejected'].includes(decision)||!String(note||'').trim())return res.status(400).json({error:'invalid_review'});
 const c=await q('select domain from cases where id=$1',[req.params.id]);if(!c.rowCount)return res.status(404).json({error:'not_found'});const id=randomUUID(),at=new Date().toISOString();
 await q('insert into reviews(id,case_id,decision,workflow_score,conversation_score,final_score,note,workflow_evidence,reviewer_id,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,req.params.id,decision,workflowScore,conversationScore,finalScore,String(note).trim(),workflowEvidence||null,req.user.id,at]);await q(`update cases set status=$1,updated_by=$2,updated_at=$3,qc_json=qc_json || jsonb_build_object('workflowScore',$5::numeric,'finalScore',$6::numeric,'workflowEvidence',$7::jsonb) where id=$4`,[decision==='referred'?'needs_review':'completed',req.user.id,at,req.params.id,workflowScore,finalScore,JSON.stringify(workflowEvidence||null)]);await audit(req.user.id,'review_submitted',{decision,workflowScore,finalScore,note},req.params.id,c.rows[0].domain);res.status(201).json({ok:true,id})
});
app.post('/api/cases/:id/ai-insight',auth(),async(req,res)=>{const model=String(req.body?.model||'local'),summary=String(req.body?.summary||'').trim();if(!summary)return res.status(400).json({error:'summary_required'});const c=await q('select domain from cases where id=$1',[req.params.id]);if(!c.rowCount)return res.status(404).json({error:'not_found'});const enc=encryptJson(summary);await q('insert into ai_insights(case_id,model,summary_iv,summary_cipher,payload,created_by) values($1,$2,$3,$4,$5,$6)',[req.params.id,model,enc.iv,enc.cipher,req.body?.payload||{},req.user.id]);await audit(req.user.id,'local_ai_insight',{model},req.params.id,c.rows[0].domain);res.status(201).json({ok:true})});
app.get('/api/audit',auth(['reviewer','supervisor','admin']),async(req,res)=>{const r=await q('select id,case_id,domain,action,detail,created_at from audit_events order by created_at desc limit 2000');res.json({audit:r.rows.map(x=>({id:x.id,caseId:x.case_id,domain:x.domain,action:x.action,detail:x.detail,createdAt:x.created_at}))})});

app.get('/api/samplers',auth(),async(_req,res)=>{const r=await q('select id,full_name as name,grade,city,active,source,created_at as "createdAt" from samplers where active=true order by full_name');res.json({samplers:r.rows})});
app.post('/api/samplers',auth(),async(req,res)=>{const name=String(req.body?.name||'').normalize('NFKC').replace(/[يى]/g,'ی').replace(/[ك]/g,'ک').replace(/\s+/g,' ').trim(),grade=String(req.body?.grade||'').trim().toUpperCase(),city=String(req.body?.city||'').trim();if(name.length<3||!grade||!city)return res.status(400).json({error:'invalid_sampler'});try{const r=await q('insert into samplers(full_name,grade,city,source) values($1,$2,$3,$4) returning id,full_name as name,grade,city,active,source,created_at as "createdAt"',[name,grade,city,'manual']);await audit(req.user.id,'sampler_created',{name,grade,city},null,'sampler');res.status(201).json({sampler:r.rows[0]})}catch(e){if(String(e?.code)==='23505')return res.status(409).json({error:'sampler_exists'});throw e}});


function ogansonAuth(req,res,next){if(!OGANSON_SECRET)return res.status(503).json({error:'oganson_secret_not_configured'});const got=String(req.get('x-oganson-token')||'');if(got!==OGANSON_SECRET)return res.status(401).json({error:'invalid_oganson_token'});next()}

app.post('/api/integrations/oganson/transcripts',ogansonAuth,async(req,res)=>{
 const b=req.body||{},domain=String(b.domain||''),externalId=String(b.externalId||'').trim(),text=String(b.text||'').trim(),subjectName=String(b.subjectName||b.personName||'').trim(),subjectKey=String(b.subjectId||b.userId||subjectName).trim();
 if(!['sampler','physician','voc'].includes(domain)||!externalId||!text||!subjectName)return res.status(400).json({error:'invalid_oganson_payload'});
 const dup=await q('select id from cases where external_source=$1 and external_id=$2 and deleted_at is null',['oganson',externalId]);if(dup.rowCount)return res.status(200).json({ok:true,deduplicated:true,caseId:dup.rows[0].id});
 let analysis;try{analysis=await analyzeTranscript({domain,text,metadata:{...b.metadata,segments:b.segments||[],oganson:b.oganson||{}}})}catch(e){await q('insert into processing_events(external_id,stage,status,detail) values($1,$2,$3,$4)',[externalId,'text_intelligence','failed',{message:String(e?.message||e)}]);return res.status(503).json({error:'text_intelligence_unavailable'})}
 const caseId=randomUUID(),tr=encryptJson(text),occurredAt=b.occurredAt?new Date(b.occurredAt):new Date(),audioHash=String(b.audioSha256||sha256('oganson|'+externalId+'|'+text));
 await tx(async db=>{
   const s=await db.query(`insert into subjects(domain,external_key,display_name,metadata) values($1,$2,$3,$4) on conflict(domain,external_key) do update set display_name=excluded.display_name,metadata=subjects.metadata||excluded.metadata,updated_at=now() returning id`,[domain,subjectKey,subjectName,b.subjectMeta||{}]),subjectId=s.rows[0].id;
   await db.query(`insert into cases(id,domain,person_name,source_name,audio_sha256,duration_seconds,transcript_iv,transcript_cipher,stt_json,qc_json,status,created_at,updated_at,occurred_at,occurred_at_ts,person_meta,subject_id,external_source,external_id,transcript_analysis_json,processing_version) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'needs_review',now(),now(),$11::date,$11,$12,$13,'oganson',$14,$15,$16)`,[caseId,domain,subjectName,String(b.sourceName||'Oganson transcript'),audioHash,Number(b.durationSeconds||0),tr.iv,tr.cipher,{provider:'oganson',externalId,confidence:b.confidence??null,segments:b.segments||[]},analysis.qc||{},occurredAt.toISOString(),b.subjectMeta||{},subjectId,externalId,analysis,analysis.version||'unknown']);
   if(domain==='voc')for(const topic of analysis.qc?.topics||[])await db.query('insert into voc_topics(case_id,topic_code,confidence,satisfaction,urgency,evidence) values($1,$2,$3,$4,$5,$6) on conflict(case_id,topic_code) do update set confidence=excluded.confidence,satisfaction=excluded.satisfaction,urgency=excluded.urgency,evidence=excluded.evidence',[caseId,topic.code,Number(topic.confidence||0),analysis.qc?.satisfaction||null,analysis.qc?.urgency||null,JSON.stringify(topic.evidence||[])]);
   await db.query('insert into processing_events(case_id,external_id,stage,status,detail) values($1,$2,$3,$4,$5)',[caseId,externalId,'ingest','completed',{domain,processingVersion:analysis.version,lexiconVersion:analysis.lexiconVersion}]);
 });
 await audit(null,'oganson_transcript_ingested',{externalId,domain,processingVersion:analysis.version},caseId,domain);
 res.status(201).json({ok:true,caseId,domain,qc:analysis.qc,entities:analysis.entities,processingVersion:analysis.version})
});

app.get('/api/profiles/:domain',auth(),async(req,res)=>{
 const domain=String(req.params.domain),calendar=String(req.query.calendar||'gregorian');if(!['sampler','physician','voc'].includes(domain))return res.status(400).json({error:'invalid_domain'});
 let from=null,to=null;try{from=req.query.from?parseDateInput(String(req.query.from),calendar):null;to=req.query.to?parseDateInput(String(req.query.to),calendar):null}catch{return res.status(400).json({error:'invalid_date_filter'})}
 const r=await q(`select coalesce(s.id,c.subject_id) subject_id,c.person_name,count(*)::int interactions,count(*) filter(where c.status='needs_review')::int review_open,count(*) filter(where jsonb_array_length(coalesce(c.qc_json->'criticalFailures','[]'::jsonb))>0)::int critical_calls,round(avg(nullif(coalesce((c.qc_json->>'finalScore')::numeric,(c.qc_json->>'conversationScore')::numeric),0)),1) avg_score,min(coalesce(c.occurred_at_ts,c.created_at)) first_at,max(coalesce(c.occurred_at_ts,c.created_at)) last_at from cases c left join subjects s on s.id=c.subject_id where c.deleted_at is null and c.domain=$1 and ($2::date is null or coalesce(c.occurred_at_ts::date,c.occurred_at,c.created_at::date)>=$2::date) and ($3::date is null or coalesce(c.occurred_at_ts::date,c.occurred_at,c.created_at::date)<=$3::date) group by coalesce(s.id,c.subject_id),c.person_name order by interactions desc,c.person_name`,[domain,from,to]);
 res.json({domain,from,to,calendar,profiles:r.rows.map(x=>({...x,avgScore:x.avg_score==null?null:Number(x.avg_score),firstDate:dualDate(x.first_at),lastDate:dualDate(x.last_at)}))})
});

app.get('/api/subjects/:id/history',auth(),async(req,res)=>{
 const r=await q('select * from cases where subject_id=$1 and deleted_at is null order by coalesce(occurred_at_ts,created_at) desc limit 5000',[req.params.id]);res.json({cases:r.rows.map(cleanCase)})
});

app.get('/api/exports/cases.csv',auth(['reviewer','supervisor','admin']),async(req,res)=>{
 const domain=req.query.domain?String(req.query.domain):null,calendar=String(req.query.calendar||'gregorian');let from=null,to=null;try{from=req.query.from?parseDateInput(String(req.query.from),calendar):null;to=req.query.to?parseDateInput(String(req.query.to),calendar):null}catch{return res.status(400).json({error:'invalid_date_filter'})}
 const r=await q(`select domain,person_name,source_name,status,qc_json,coalesce(occurred_at_ts,created_at) at from cases where deleted_at is null and ($1::text is null or domain=$1) and ($2::date is null or coalesce(occurred_at_ts::date,occurred_at,created_at::date)>=$2::date) and ($3::date is null or coalesce(occurred_at_ts::date,occurred_at,created_at::date)<=$3::date) order by at desc`,[domain,from,to]);
 const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"',rows=[['domain','person','source','status','score','risk','date_gregorian','date_jalali'].join(',')];for(const x of r.rows){const dd=dualDate(x.at),score=x.qc_json?.finalScore??x.qc_json?.conversationScore??'',risk=x.qc_json?.risk??'';rows.push([x.domain,x.person_name,x.source_name,x.status,score,risk,dd.gregorian,dd.jalali].map(esc).join(','))}
 res.setHeader('content-type','text/csv; charset=utf-8');res.setHeader('content-disposition','attachment; filename="kuleposhti-cases.csv"');res.send('\ufeff'+rows.join('\n'))
});

app.get('/api/users',auth(['admin']),async(_req,res)=>{const r=await q('select id,email,display_name as "displayName",role,active,created_at as "createdAt" from users order by created_at');res.json({users:r.rows})});
app.post('/api/users',auth(['admin']),async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase(),display=String(req.body?.displayName||'').trim(),role=String(req.body?.role||''),password=String(req.body?.password||'');if(!email||!display||!['operator','reviewer','supervisor','admin'].includes(role))return res.status(400).json({error:'invalid_user'});const pr=passwordRecord(password);const r=await q('insert into users(email,display_name,password_salt,password_hash,role) values($1,$2,$3,$4,$5) returning id,email,display_name as "displayName",role,active',[email,display,pr.salt,pr.hash,role]);await audit(req.user.id,'user_created',{email,role});res.status(201).json({user:r.rows[0]})});
app.patch('/api/users/:id',auth(['admin']),async(req,res)=>{const active=Boolean(req.body?.active),role=req.body?.role;if(role&&!['operator','reviewer','supervisor','admin'].includes(role))return res.status(400).json({error:'invalid_role'});await q('update users set active=$1,role=coalesce($2,role) where id=$3',[active,role||null,req.params.id]);await audit(req.user.id,'user_updated',{target:req.params.id,active,role});res.json({ok:true})});

app.get('/api/rule-packs',auth(),async(req,res)=>{const r=await q('select id,domain,version,status,sha256,content_json as content,created_at as "createdAt" from rule_packs order by created_at desc');res.json({rulePacks:r.rows})});
app.post('/api/rule-packs',auth(['supervisor','admin']),async(req,res)=>{const{domain,version,status='candidate',content}=req.body||{};if(!['sampler','physician'].includes(domain)||!version||!content)return res.status(400).json({error:'invalid_rule_pack'});const hash=sha256(JSON.stringify(content));await q('insert into rule_packs(domain,version,status,sha256,content_json,created_by) values($1,$2,$3,$4,$5,$6)',[domain,version,status,hash,content,req.user.id]);await audit(req.user.id,'rule_pack_created',{domain,version,status,sha256:hash},null,domain);res.status(201).json({ok:true,sha256:hash})});

app.use((err,req,res,_next)=>{console.error(err);res.status(500).json({error:'internal_error',requestId:req.get('x-request-id')||null})});
await bootstrapAdmin();app.listen(PORT,'0.0.0.0',()=>console.log('KulePoshti team API listening',PORT));
