import{randomUUID}from'node:crypto';
import jalaali from'jalaali-js';
import{q}from'./db.mjs';
import{encryptJson,decryptJson}from'./crypto.mjs';
import{analyzeTranscript,INTELLIGENCE_VERSION}from'./intelligence/index.mjs';
import{canonicalOgansonPayload,fetchOgansonTranscript,ogansonHealth,verifyOgansonWebhook,OGANSON_CONTRACT_VERSION}from'./oganson.mjs';

const jd=v=>{const m=/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})$/.exec(String(v||'').trim());if(!m)throw new Error('invalid_jalali_date');const g=jalaali.toGregorian(+m[1],+m[2],+m[3]);return [g.gy,String(g.gm).padStart(2,'0'),String(g.gd).padStart(2,'0')].join('-')};
const gj=v=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return null;const j=jalaali.toJalaali(d.getUTCFullYear(),d.getUTCMonth()+1,d.getUTCDate());return [j.jy,String(j.jm).padStart(2,'0'),String(j.jd).padStart(2,'0')].join('-')};
const plus1=s=>{const d=new Date(s+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)};
function range(query={}){let from=String(query.from||'').trim(),to=String(query.to||'').trim();if(query.fromJalali)from=jd(query.fromJalali);if(query.toJalali)to=jd(query.toJalali);return{from:from?from+'T00:00:00+03:30':null,toExclusive:to?plus1(to)+'T00:00:00+03:30':null}}
async function iaudit(actorId,action,detail={},interactionId=null,domain=null){await q('insert into interaction_audit_events(interaction_id,actor_id,domain,action,detail) values($1,$2,$3,$4,$5)',[interactionId,actorId,domain,action,detail])}
async function subject(domain,s,fallback=''){
 const ext=String(s?.externalId||fallback||'').trim()||null,name=String(s?.name||'').trim()||(domain==='physician'?'پزشک نامشخص':domain==='sampler'?'نمونه‌گیر نامشخص':'کاربر');
 if(ext){const x=await q('select id from subjects where domain=$1 and external_id=$2',[domain,ext]);if(x.rowCount){await q('update subjects set display_name=$2,updated_at=now() where id=$1',[x.rows[0].id,name]);return x.rows[0].id}const r=await q('insert into subjects(domain,external_id,display_name) values($1,$2,$3) returning id',[domain,ext,name]);return r.rows[0].id}
 const x=await q('select id from subjects where domain=$1 and display_name=$2 order by created_at limit 1',[domain,name]);if(x.rowCount)return x.rows[0].id;const r=await q('insert into subjects(domain,display_name) values($1,$2) returning id',[domain,name]);return r.rows[0].id
}
function rowOut(r,detail=false){const x={id:r.id,externalId:r.external_id,sourceProvider:r.source_provider,domain:r.domain,subjectId:r.subject_id,subjectName:r.subject_name,subjectExternalId:r.subject_external_id,customerExternalId:r.customer_external_id,sourceName:r.source_name,occurredAt:r.occurred_at,jalaliDate:gj(r.occurred_at),asrConfidence:r.asr_confidence==null?null:Number(r.asr_confidence),score:r.score==null?null:Number(r.score),scoreStatus:r.score_status,risk:r.risk,primaryTopic:r.primary_topic,sentiment:r.sentiment,satisfaction:r.satisfaction,status:r.status,engineVersion:r.engine_version,rulePackVersion:r.rule_pack_version,createdAt:r.created_at,updatedAt:r.updated_at};if(detail){x.transcript=decryptJson(r.transcript_iv,r.transcript_cipher);x.analysis=decryptJson(r.analysis_iv,r.analysis_cipher)}return x}
async function ingest(payload,{actorId=null,sourceProvider='oganson'}={}){
 const p=canonicalOgansonPayload(payload);if(!['sampler','physician','voc'].includes(p.domain))throw Object.assign(new Error('invalid_domain'),{status:400});if(!p.externalId)throw Object.assign(new Error('external_id_required'),{status:400});if(!p.transcript)throw Object.assign(new Error('transcript_required'),{status:400});
 const occurred=new Date(p.occurredAt);if(Number.isNaN(occurred.getTime()))throw Object.assign(new Error('invalid_occurred_at'),{status:400});
 const sid=await subject(p.domain,p.subject,p.domain==='voc'?(p.customerExternalId||'anonymous:'+p.externalId):'');
 const intelligence=analyzeTranscript({domain:p.domain,transcript:p.transcript,metadata:{...p.metadata,asrConfidence:p.asrConfidence,language:p.language,segmentCount:p.segments.length}}),a=intelligence.analysis;
 const tr=encryptJson(p.transcript),raw=encryptJson({segments:p.segments,language:p.language,metadata:p.metadata}),ae=encryptJson(intelligence),id=randomUUID(),score=a.conversationScore??null,scoreStatus=a.scoreStatus||'review_required',status=scoreStatus==='non_scorable'?'non_scorable':'needs_review';
 try{
  await q('insert into interactions(id,external_id,source_provider,domain,subject_id,customer_external_id,source_name,occurred_at,transcript_iv,transcript_cipher,payload_iv,payload_cipher,analysis_iv,analysis_cipher,asr_confidence,score,score_status,risk,primary_topic,sentiment,satisfaction,status,engine_version,rule_pack_version,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25)',[id,p.externalId,sourceProvider,p.domain,sid,p.customerExternalId||null,p.sourceName,occurred.toISOString(),tr.iv,tr.cipher,raw.iv,raw.cipher,ae.iv,ae.cipher,p.asrConfidence,score,scoreStatus,a.risk||a.urgency||null,a.primaryTopic||null,a.sentiment||null,a.satisfaction||null,status,INTELLIGENCE_VERSION,a.version||null,actorId]);
 }catch(e){if(String(e?.code)==='23505'){const x=await q('select id from interactions where source_provider=$1 and external_id=$2',[sourceProvider,p.externalId]);return{duplicate:true,id:x.rows[0]?.id||null,intelligence}}throw e}
 await iaudit(actorId,'interaction_ingested',{sourceProvider,externalId:p.externalId,scoreStatus,score,primaryTopic:a.primaryTopic||null,sentiment:a.sentiment||null},id,p.domain);return{duplicate:false,id,intelligence}
}
function where(query,params,skipDomain=false){const w=['1=1'];let n=params.length+1;if(query.domain&&!skipDomain){w.push('i.domain=$'+n++);params.push(String(query.domain))}if(query.subjectId){w.push('i.subject_id=$'+n++);params.push(String(query.subjectId))}if(query.topic){w.push('i.primary_topic=$'+n++);params.push(String(query.topic))}if(query.sentiment){w.push('i.sentiment=$'+n++);params.push(String(query.sentiment))}if(query.satisfaction){w.push('i.satisfaction=$'+n++);params.push(String(query.satisfaction))}const z=range(query);if(z.from){w.push('i.occurred_at >= $'+n++);params.push(z.from)}if(z.toExclusive){w.push('i.occurred_at < $'+n++);params.push(z.toExclusive)}return w.join(' and ')}
const csv=v=>{const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s};

export function registerIntelligenceRoutes(app,{auth}){
 app.get('/api/v2/intelligence/health',auth(),async(_req,res)=>res.json({ok:true,intelligenceVersion:INTELLIGENCE_VERSION,ogansonContractVersion:OGANSON_CONTRACT_VERSION,oganson:await ogansonHealth()}));
 app.post('/api/v2/intelligence/analyze',auth(),async(req,res)=>{try{res.json(analyzeTranscript({domain:req.body?.domain,transcript:req.body?.transcript,metadata:req.body?.metadata||{}}))}catch(e){res.status(400).json({error:String(e?.message||e)})}});
 app.post('/api/v2/integrations/oganson/ingest',async(req,res)=>{if(!verifyOgansonWebhook(req))return res.status(401).json({error:'invalid_oganson_token'});try{const out=await ingest(req.body,{sourceProvider:'oganson'});res.status(out.duplicate?200:201).json(out)}catch(e){res.status(e?.status||500).json({error:String(e?.message||e)})}});
 app.post('/api/v2/integrations/oganson/pull/:jobId',auth(),async(req,res)=>{try{const p=await fetchOgansonTranscript(req.params.jobId),out=await ingest(p.raw,{actorId:req.user.id,sourceProvider:'oganson'});res.status(out.duplicate?200:201).json(out)}catch(e){res.status(502).json({error:String(e?.message||e)})}});
 app.get('/api/v2/interactions',auth(),async(req,res)=>{try{const p=[],w=where(req.query,p),limit=Math.min(2000,Math.max(1,Number(req.query.limit||500)));p.push(limit);const sql='select i.*,s.display_name subject_name,s.external_id subject_external_id from interactions i join subjects s on s.id=i.subject_id where '+w+' order by i.occurred_at desc limit $'+p.length,r=await q(sql,p);res.json({interactions:r.rows.map(x=>rowOut(x,false))})}catch(e){res.status(400).json({error:String(e?.message||e)})}});
 app.get('/api/v2/interactions/:id',auth(),async(req,res)=>{const r=await q('select i.*,s.display_name subject_name,s.external_id subject_external_id from interactions i join subjects s on s.id=i.subject_id where i.id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json({interaction:rowOut(r.rows[0],true)})});
 app.post('/api/v2/interactions/:id/reviews',auth(['reviewer','supervisor','admin']),async(req,res)=>{const decision=String(req.body?.decision||''),note=String(req.body?.note||'').trim();if(!['approved','referred','overridden','rejected'].includes(decision)||!note)return res.status(400).json({error:'invalid_review'});const x=await q('select * from interactions where id=$1',[req.params.id]);if(!x.rowCount)return res.status(404).json({error:'not_found'});const finalScore=req.body?.finalScore==null?x.rows[0].score:Number(req.body.finalScore);await q('insert into interaction_reviews(interaction_id,decision,final_score,note,evidence,reviewer_id) values($1,$2,$3,$4,$5,$6)',[req.params.id,decision,finalScore,note,req.body?.evidence||null,req.user.id]);await q('update interactions set status=$2,score=coalesce($3,score),updated_at=now() where id=$1',[req.params.id,decision==='referred'?'needs_review':'completed',finalScore]);await iaudit(req.user.id,'interaction_reviewed',{decision,finalScore,note},req.params.id,x.rows[0].domain);res.status(201).json({ok:true})});
 app.get('/api/v2/profiles',auth(),async(req,res)=>{try{const p=[],w=where(req.query,p,true),domain=String(req.query.domain||'');if(domain){p.unshift(domain)}const domainClause=domain?'s.domain=$1 and ':'',shift=domain?1:0,ww=shift?w.replace(/\$(\d+)/g,(_,n)=>'$'+(+n+1)):w,r=await q('select s.id,s.domain,s.external_id,s.display_name,count(i.id)::int interactions,round(avg(i.score)::numeric,1) avg_score,count(*) filter(where i.status=\\'needs_review\\')::int open_review,count(*) filter(where i.risk in(\\'critical\\',\\'urgent_review\\'))::int critical_count,count(*) filter(where i.satisfaction=\\'dissatisfied\\')::int dissatisfied_count,max(i.occurred_at) last_interaction from subjects s join interactions i on i.subject_id=s.id where '+domainClause+ww+' group by s.id order by last_interaction desc',p);res.json({profiles:r.rows.map(x=>({...x,jalaliLastInteraction:gj(x.last_interaction)}))})}catch(e){res.status(400).json({error:String(e?.message||e)})}});
 app.get('/api/v2/profiles/:id/history',auth(),async(req,res)=>{try{const p=[req.params.id],w=where(req.query,p),r=await q('select i.*,s.display_name subject_name,s.external_id subject_external_id from interactions i join subjects s on s.id=i.subject_id where i.subject_id=$1 and '+w+' order by i.occurred_at desc limit 2000',p);res.json({history:r.rows.map(x=>rowOut(x,false))})}catch(e){res.status(400).json({error:String(e?.message||e)})}});
 app.get('/api/v2/export.csv',auth(['reviewer','supervisor','admin']),async(req,res)=>{try{const p=[],w=where(req.query,p),r=await q('select i.*,s.display_name subject_name,s.external_id subject_external_id from interactions i join subjects s on s.id=i.subject_id where '+w+' order by i.occurred_at desc limit 10000',p),inc=req.query.includeTranscript==='1'&&['supervisor','admin'].includes(req.user.role),head=['id','domain','subject','subject_external_id','customer_external_id','occurred_at','jalali_date','score','score_status','risk','topic','sentiment','satisfaction','status',...(inc?['transcript']:[])],lines=[head.join(',')];for(const r of r.rows){const v=[r.id,r.domain,r.subject_name,r.subject_external_id,r.customer_external_id,new Date(r.occurred_at).toISOString(),gj(r.occurred_at),r.score,r.score_status,r.risk,r.primary_topic,r.sentiment,r.satisfaction,r.status];if(inc)v.push(decryptJson(r.transcript_iv,r.transcript_cipher));lines.push(v.map(csv).join(','))}res.setHeader('content-type','text/csv; charset=utf-8');res.setHeader('content-disposition','attachment; filename="kuleposhti-export.csv"');res.send('\uFEFF'+lines.join('\n'))}catch(e){res.status(400).json({error:String(e?.message||e)})}});
}
