import{pipeline,env as hfEnv}from'@huggingface/transformers';import{choosePlan,getMode,probeHardware,setMode,type HardwareProfile,type ModelMode,type ModelPlan}from'./modelPolicy';
type Progress=(p:{status:string;progress?:number;file?:string;model?:string})=>void;type Loaded={pipe:any,plan:ModelPlan,hardware:HardwareProfile,fallbackReason?:string};const cache=new Map<string,Promise<Loaded>>();
async function create(plan:ModelPlan,h:HardwareProfile,progress:Progress):Promise<Loaded>{hfEnv.allowLocalModels=false;hfEnv.allowRemoteModels=true;hfEnv.useBrowserCache=true;(hfEnv as any).useWasmCache=true;(hfEnv as any).cacheKey='kp-whisper-v1';try{const pipe=await pipeline('automatic-speech-recognition',plan.id,{device:plan.device,dtype:plan.dtype,progress_callback:(x:any)=>progress({status:String(x.status||'loading'),progress:Number(x.progress||0),file:x.file,model:plan.label})}as any);return{pipe,plan,hardware:h}}catch(e){if(!plan.fallbackId)throw e;const p:ModelPlan={...plan,id:'onnx-community/whisper-small',label:'Whisper Small · fallback',device:h.webgpu?'webgpu':'wasm',dtype:h.webgpu?'fp16':'q8',fallbackId:null,reason:'Fallback after model load failure'};const pipe=await pipeline('automatic-speech-recognition',p.id,{device:p.device,dtype:p.dtype,progress_callback:(x:any)=>progress({status:String(x.status||'loading'),progress:Number(x.progress||0),file:x.file,model:p.label})}as any);return{pipe,plan:p,hardware:h,fallbackReason:e instanceof Error?e.message:String(e)}}}
export async function modelStatus(mode:ModelMode=getMode()){const h=await probeHardware(),plan=choosePlan(mode,h);return{mode,hardware:h,plan,cacheEnabled:Boolean('caches'in globalThis),policy:'browser-asr-policy-1.0.0'}}
export function setModelMode(mode:ModelMode){setMode(mode);cache.clear()}
export async function warmModel(mode:ModelMode,progress:Progress){setModelMode(mode);const h=await probeHardware(),p=choosePlan(mode,h),k=p.id+'|'+p.device+'|'+JSON.stringify(p.dtype);if(!cache.has(k))cache.set(k,create(p,h,progress));return cache.get(k)!}
async function decode16k(file:File){const raw=await file.arrayBuffer(),ctx=new AudioContext(),decoded=await ctx.decodeAudioData(raw.slice(0));await ctx.close();const rate=16000,len=Math.ceil(decoded.duration*rate),off=new OfflineAudioContext(1,len,rate),src=off.createBufferSource(),mono=off.createBuffer(1,decoded.length,decoded.sampleRate),dst=mono.getChannelData(0);for(let c=0;c<decoded.numberOfChannels;c++){const ch=decoded.getChannelData(c);for(let i=0;i<ch.length;i++)dst[i]+=ch[i]/decoded.numberOfChannels}src.buffer=mono;src.connect(off.destination);src.start();const out=await off.startRendering();return out.getChannelData(0)}
function activity(a:Float32Array){let peak=0,sum=0;for(const x of a){const v=Math.abs(x);if(v>peak)peak=v;sum+=x*x}const rms=Math.sqrt(sum/Math.max(1,a.length));return{peak,rms,noSpeech:peak<.002&&rms<.0005}}
export async function sha256File(file:File){const h=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function transcribe(file:File,progress:Progress,mode:ModelMode=getMode()){const t0=performance.now();progress({status:'decode'});const audio=await decode16k(file),act=activity(audio),durationSeconds=audio.length/16000;if(act.noSpeech)return{text:'',chunks:[],durationSeconds,noSpeech:true,activity:act,device:'none',modelId:null,modelMode:mode,rtf:0};const loaded=await warmModel(mode,progress);progress({status:'transcribe',model:loaded.plan.label});const out=await loaded.pipe(audio,{language:'fa',task:'transcribe',chunk_length_s:30,stride_length_s:5,return_timestamps:true});const chunks=(out.chunks||[]).map((x:any)=>({text:String(x.text||'').trim(),timestamp:Array.isArray(x.timestamp)?x.timestamp:[null,null]}));const elapsed=(performance.now()-t0)/1000;return{text:String(out.text||'').trim(),chunks,durationSeconds,noSpeech:false,activity:act,device:loaded.plan.device,modelId:loaded.plan.id,modelLabel:loaded.plan.label,modelMode:mode,dtype:loaded.plan.dtype,rtf:durationSeconds?Number((elapsed/durationSeconds).toFixed(3)):null,fallbackReason:loaded.fallbackReason||null,hardware:loaded.hardware}}
