import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,BarChart3,BrainCircuit,ChevronLeft,ClipboardCheck,Database,Download,Eye,FileAudio,Home,Lock,Menu,Play,RefreshCw,Search,Settings,ShieldCheck,Square,Stethoscope,Trash2,Upload,Users,UserRoundSearch,X}from'lucide-react';
import{sha256File,transcribe,modelStatus,setModelMode,warmModel}from'./asr';
import{getMode,requestPersistentStorage,type ModelMode}from'./modelPolicy';
import{hasVault,initVault,unlockVault,lockVault,putCase,listCases,existsHash,submitReview,deleteCase,exportBackup,importBackup,listAudit,saveAiInsight,type CaseRecord,type AuditEvent}from'./vault';
import{scoreGold,type GoldCase}from'./qualityGate';
import{evaluateConversation,scoreWorkflow,CONVERSATION_RULES,WORKFLOW_POLICY,type WorkflowEvidence}from'./qcEngine';
import{evaluatePhysician,PHYSICIAN_RULES}from'./physicianQcEngine';
import{executive,filtered,pareto,people,riskDistribution,weeklyTrend}from'./analytics';
import{DOMAIN_META,type QcDomain}from'./domain';
import{localQcCopilot}from'./localAi';
import'./styles.css';

const fa=new Intl.NumberFormat('fa-IR',{maximumFractionDigits:1});
type Tab='home'|'upload'|'review'|'people'|'report'|'qc'|'model'|'system';
type Row={key:string;file:File;personName:string;status:'queued'|'running'|'done'|'failed';message:string;manualText?:string};

const emptyWorkflow:WorkflowEvidence={nightAttempts:0,twentyMinuteSpacing:'unknown',morningRetry:'unknown',userAnswered:'unknown',finalStatus:'unknown',coordinationRecorded:'unknown',reviewerNote:''};

function VaultGate({done}:{done:()=>void}){const[existing,setExisting]=useState<boolean|null>(null),[p,setP]=useState(''),[m,setM]=useState('');useEffect(()=>{hasVault().then(setExisting).catch(e=>{setM(e?.message||'Storage مرورگر در دسترس نیست');setExisting(false)})},[]);if(existing===null)return<div className="loading">در حال آماده‌سازی Vault…</div>;return<main className="login"><section><div className="brandmark"><ShieldCheck size={28}/></div><h1>کوله‌پشتی</h1><p>مرکز کنترل کیفیت مکالمات فارسی</p><div className="login-copy">{existing?'Passphrase محلی Vault را وارد کنید.':'برای این مرورگر یک Vault رمزگذاری‌شده بسازید.'}</div><input type="password" placeholder="Passphrase حداقل ۱۲ کاراکتر" value={p} onChange={e=>setP(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')(e.currentTarget.nextElementSibling as HTMLButtonElement)?.click()}}/><button className="primary xl" onClick={async()=>{try{existing?await unlockVault(p):await initVault(p);done()}catch(e:any){setM(e.message||'خطا')}}}>{existing?'ورود به کوله‌پشتی':'ساخت Vault و ورود'}</button><small>Passphrase و فایل صوتی به هیچ سروری ارسال نمی‌شوند.</small>{m&&<b className="err">{m}</b>}</section></main>}

function Sparkline({rows}:{rows:{label:string;avg:number;count:number}[]}){const vals=rows.map(x=>x.avg),max=Math.max(100,...vals),min=0,w=640,h=180,p=20;const pts=rows.map((x,i)=>{const xx=p+i*((w-p*2)/Math.max(1,rows.length-1)),yy=h-p-((x.avg-min)/(max-min||1))*(h-p*2);return[xx,yy]});return<div className="chartbox"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="روند امتیاز"><line x1="20" y1="160" x2="620" y2="160" className="gridline"/><line x1="20" y1="90" x2="620" y2="90" className="gridline"/><line x1="20" y1="20" x2="620" y2="20" className="gridline"/><polyline fill="none" className="trendline" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" points={pts.map(x=>x.join(',')).join(' ')}/>{pts.map((x,i)=><circle key={i} cx={x[0]} cy={x[1]} r="4.5" className="trenddot"><title>{rows[i].label}: {rows[i].avg||'بدون داده'}</title></circle>)}</svg><div className="axislabels">{rows.map(x=><span key={x.label}>{x.label}</span>)}</div></div>}

function RiskDonut({r}:{r:{low:number;medium:number;high:number;critical:number}}){const total=r.low+r.medium+r.high+r.critical;if(!total)return<div className="empty compact">داده کافی وجود ندارد.</div>;const a=r.low/total*360,b=a+r.medium/total*360,c=b+r.high/total*360;return<div className="riskwrap"><div className="donut" style={{background:`conic-gradient(var(--good) 0 ${a}deg,var(--mid) ${a}deg ${b}deg,var(--high) ${b}deg ${c}deg,var(--critical) ${c}deg 360deg)`}}><div><b>{fa.format(total)}</b><span>پرونده</span></div></div><div className="legend"><span><i className="low"/>کم‌ریسک <b>{r.low}</b></span><span><i className="medium"/>متوسط <b>{r.medium}</b></span><span><i className="high"/>بالا <b>{r.high}</b></span><span><i className="critical"/>بحرانی <b>{r.critical}</b></span></div></div>}

function Pareto({rows}:{rows:{id:string;label:string;count:number;critical:boolean}[]}){const max=Math.max(1,...rows.map(x=>x.count));return<div className="pareto">{rows.length?rows.map(x=><div key={x.id}><div className="pareto-head"><span><b>{x.id}</b> {x.label}{x.critical&&<em>Critical</em>}</span><strong>{fa.format(x.count)}</strong></div><div className="bar"><i style={{width:`${x.count/max*100}%`}}/></div></div>):<div className="empty compact">هنوز خطای تکرارشونده‌ای ثبت نشده است.</div>}</div>}

function Calibration({onRun,gold}:{onRun:(m:File|null,f:FileList|null)=>void;gold:any}){const[m,setM]=useState<File|null>(null),[f,setF]=useState<FileList|null>(null);const g=gold?.gate||{},x=gold?.metrics||{};return<article className="panel"><div className="panel-title"><div><h3>Gold Calibration</h3><p>Smoke ≥۲۰ و Production ≥۵۰ فایل adjudicated.</p></div><ShieldCheck/></div><label>Manifest JSON<input type="file" accept=".json" onChange={e=>setM(e.target.files?.[0]||null)}/></label><label>فایل‌های Gold<input type="file" multiple accept="audio/*" onChange={e=>setF(e.target.files)}/></label><button className="primary" onClick={()=>onRun(m,f)}>اجرای Benchmark محلی</button>{gold&&<><div className="score-row"><div><span>WER</span><b>{fa.format(x.wer??0)}%</b></div><div><span>RTF</span><b>{fa.format(x.rtf??0)}</b></div><div><span>Cases</span><b>{fa.format(x.cases??0)}</b></div></div><div className="gategrid"><span className={g.smokeCases?'pass':'fail'}>Smoke ≥20</span><span className={g.productionCases?'pass':'fail'}>Production ≥50</span><span className={g.criticalRecall?'pass':'fail'}>Critical Recall</span><span className={g.numberRecall?'pass':'fail'}>Number Recall</span><span className={g.negationRecall?'pass':'fail'}>Negation</span><span className={g.silence?'pass':'fail'}>Silence</span></div></>}</article>}

function App(){
 const[unlocked,setUnlocked]=useState(false),[domain,setDomain]=useState<QcDomain>('sampler'),[tab,setTab]=useState<Tab>('home'),[sidebar,setSidebar]=useState(false),[cases,setCases]=useState<CaseRecord[]>([]),[audit,setAudit]=useState<AuditEvent[]>([]),[rows,setRows]=useState<Row[]>([]),[person,setPerson]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[selected,setSelected]=useState<CaseRecord|null>(null),[note,setNote]=useState(''),[mode,setModeState]=useState<ModelMode>(getMode()),[modelInfo,setModelInfo]=useState<any>(null),[gold,setGold]=useState<any>(null),[wf,setWf]=useState<WorkflowEvidence>(emptyWorkflow),[aiBusy,setAiBusy]=useState(false),[query,setQuery]=useState(''),stop=useRef(false);
 async function load(){if(!unlocked)return;setCases(await listCases());setAudit(await listAudit().catch(()=>[]));setModelInfo(await modelStatus(mode).catch(()=>null))}
 useEffect(()=>{load()},[unlocked,mode]);
 const xs=useMemo(()=>filtered(cases,domain),[cases,domain]),stats=useMemo(()=>executive(cases,domain),[cases,domain]),profiles=useMemo(()=>people(cases,domain),[cases,domain]),trend=useMemo(()=>weeklyTrend(cases,domain),[cases,domain]),risks=useMemo(()=>riskDistribution(cases,domain),[cases,domain]),failures=useMemo(()=>pareto(cases,domain),[cases,domain]);
 const reviewRows=useMemo(()=>xs.filter(x=>!query||x.personName.includes(query)||x.sourceName.includes(query)||x.transcript.includes(query)),[xs,query]);
 if(!unlocked)return<VaultGate done={()=>setUnlocked(true)}/>;
 const meta=DOMAIN_META[domain];
 function changeDomain(d:QcDomain){setDomain(d);setRows([]);setPerson('');setSelected(null);setMsg('')}
 function pick(fs:FileList|null){if(!fs)return;setRows([...fs].slice(0,100).map((file,i)=>({key:i+'-'+file.name+'-'+file.size,file,personName:person,status:'queued',message:'در صف'})))}
 function patch(k:string,p:Partial<Row>){setRows(r=>r.map(x=>x.key===k?{...x,...p}:x))}
 function evaluate(text:string){return domain==='sampler'?evaluateConversation(text):evaluatePhysician(text)}
 async function saveFromText(row:Row,hash:string,text:string,stt:any){if(!text.trim())throw new Error('Transcript خالی است');if(await existsHash(hash))throw new Error('فایل تکراری است');const now=new Date().toISOString(),rec:CaseRecord={id:crypto.randomUUID(),domain,personName:(row.personName||person).trim(),sourceName:row.file.name,audioSha256:hash,durationSeconds:Number(stt.durationSeconds||0),transcript:text.trim(),stt,qc:evaluate(text),status:'needs_review',reviews:[],createdAt:now,updatedAt:now};await putCase(rec)}
 async function run(){if(!rows.length)return;stop.current=false;setBusy(true);for(const row of rows){if(stop.current)break;if(row.status==='done')continue;try{const name=(row.personName||person).trim();if(!name)throw new Error(`نام ${meta.personLabel} خالی است`);patch(row.key,{status:'running',message:'محاسبه Hash'});const hash=await sha256File(row.file);if(await existsHash(hash))throw new Error('فایل تکراری است');const stt=await transcribe(row.file,p=>{setProgress((p.model?p.model+' · ':'')+p.status+(p.progress?' '+Math.round(p.progress)+'%':''));patch(row.key,{message:p.status})},mode);if(stt.noSpeech)throw new Error('سکوت/عدم گفتار');if(stt.text.length<10)throw new Error('Transcript ناکافی');await saveFromText(row,hash,stt.text,stt);patch(row.key,{status:'done',message:'QC آماده Review'})}catch(e:any){patch(row.key,{status:'failed',message:e.message||'خطا'})}}setBusy(false);setProgress('');await load();setMsg(stop.current?'پردازش بعد از فایل جاری متوقف شد.':'Batch پردازش شد و پرونده‌ها وارد صف Review شدند.')}
 async function manual(row:Row){const text=prompt('Transcript دستی این فایل را وارد کنید:',row.manualText||'');if(!text)return;try{const hash=await sha256File(row.file);await saveFromText(row,hash,text,{device:'manual',modelId:'manual',durationSeconds:0});patch(row.key,{status:'done',message:'ثبت دستی'});await load()}catch(e:any){setMsg(e.message)}}
 async function review(dec:'approved'|'referred'|'overridden'){if(!selected||!note.trim())return setMsg('یادداشت Reviewer الزامی است.');if(selected.qc?.criticalFailures?.length&&dec==='approved')return setMsg('Critical Failure باز است؛ ارجاع یا Override مستند لازم است.');let workflow:number|null=null,evidence:any=undefined;if(selected.domain==='sampler'){const w=scoreWorkflow({...wf,reviewerNote:note});if(w.issues.length&&dec==='approved')return setMsg('Workflow Evidence ناقص است: '+w.issues.join(' | '));workflow=w.workflowScore;evidence={...wf,reviewerNote:note,policyVersion:w.policyVersion,issues:w.issues}}await submitReview(selected.id,dec,workflow,note,evidence);setSelected(null);setNote('');setWf(emptyWorkflow);await load();setMsg('Review و Audit ثبت شد.')}
 async function aiAssist(){if(!selected)return;setAiBusy(true);try{setMsg('AI محلی در حال تحلیل است؛ نتیجه فقط Copilot است و امتیاز را تغییر نمی‌دهد.');const insight=await localQcCopilot(selected.transcript,selected.domain,s=>setMsg(s));await saveAiInsight(selected.id,insight);setSelected({...selected,aiInsight:insight});await load();setMsg('تحلیل AI محلی ذخیره شد.')}catch(e:any){setMsg('AI محلی آماده نشد: '+(e.message||e))}finally{setAiBusy(false)}}
 function csv(){const h=['Domain','Person','File','Status','Conversation','Workflow','Final','Risk','CreatedAt'];const lines=[h.join(','),...xs.map(x=>[x.domain,x.personName,x.sourceName,x.status,x.qc?.conversationScore??'',x.qc?.workflowScore??'',x.qc?.finalScore??'',x.qc?.risk??'',x.createdAt].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))];download(new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),`kuleposhti-${domain}-report.csv`)}
 function download(b:Blob,n:string){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 async function backup(){download(new Blob([JSON.stringify(await exportBackup())],{type:'application/json'}),'kuleposhti-encrypted-backup-v2.json')}
 async function restore(file:File|null){if(!file)return;try{await importBackup(JSON.parse(await file.text()));lockVault();setUnlocked(false);setMsg('Backup وارد شد؛ با Passphrase همان Backup باز کنید.')}catch(e:any){setMsg(e.message)}}
 async function warm(){setMsg('در حال دانلود/Cache مدل…');await requestPersistentStorage();try{await warmModel(mode,p=>setProgress((p.model?p.model+' · ':'')+p.status+(p.progress?' '+Math.round(p.progress)+'%':'')));setModelInfo(await modelStatus(mode));setMsg('مدل آماده شد.')}catch(e:any){setMsg('مدل آماده نشد: '+e.message)}finally{setProgress('')}}
 async function calibrate(manifestFile:File|null,audioFiles:FileList|null){if(!manifestFile||!audioFiles)return;const manifest=JSON.parse(await manifestFile.text()),map=new Map([...audioFiles].map(f=>[f.name,f])),out:GoldCase[]=[];for(let i=0;i<manifest.length;i++){const g=manifest[i],f=map.get(g.fileName);if(!f)continue;const t0=performance.now(),r=await transcribe(f,p=>setProgress('Gold '+(i+1)+'/'+manifest.length+' · '+p.status),mode);out.push({id:g.id,reference:g.reference,hypothesis:r.text,criticalTerms:g.criticalTerms,numbers:g.numbers,negations:g.negations,silence:g.silence,durationSeconds:r.durationSeconds,elapsedSeconds:(performance.now()-t0)/1000})}setGold({rows:out,...scoreGold(out)});setProgress('')}
 const nav:[[Tab,string,any],...any[]]=[['home','مرکز فرماندهی',Home],['upload','ورودی مکالمات',Upload],['review','صف بررسی',ClipboardCheck],['people',meta.label,Users],['report','گزارش‌ها',BarChart3],['qc','قواعد QC',ShieldCheck],['model','AI و مدل‌ها',BrainCircuit],['system','سیستم و بازیابی',Settings]];
 return<div className="app-shell">
  <aside className={sidebar?'sidebar open':'sidebar'}>
   <div className="side-brand"><div className="logo"><Activity/></div><div><b>کوله‌پشتی</b><span>QC Operations OS</span></div><button className="mobile-close" onClick={()=>setSidebar(false)}><X/></button></div>
   <div className="domain-switch"><button className={domain==='physician'?'active':''} onClick={()=>changeDomain('physician')}><Stethoscope/>پزشکان</button><button className={domain==='sampler'?'active':''} onClick={()=>changeDomain('sampler')}><FileAudio/>نمونه‌گیران</button></div>
   <div className="nav-label">فضای کاری {meta.label}</div>
   <nav>{nav.map(([id,label,I])=><button key={id} className={tab===id?'on':''} onClick={()=>{setTab(id);setSidebar(false)}}><I/><span>{label}</span>{id==='review'&&stats.reviewOpen>0&&<em>{fa.format(stats.reviewOpen)}</em>}</button>)}</nav>
   <div className="side-foot"><div><span className="status-dot"/><b>Local-first</b></div><small>Audio Cloud = 0 · Paid AI = 0</small></div>
  </aside>
  {sidebar&&<div className="scrim" onClick={()=>setSidebar(false)}/>}
  <section className="workspace">
   <header className="topbar"><button className="hamb" onClick={()=>setSidebar(true)}><Menu/></button><div><span className="crumb">کوله‌پشتی / {meta.label}</span><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="top-actions"><div className="privacy-pill"><ShieldCheck/>Evidence-first</div><button onClick={()=>{lockVault();setUnlocked(false)}}><Lock/>قفل</button></div></header>
   <main className="content">{msg&&<div className="toast">{msg}<button onClick={()=>setMsg('')}>×</button></div>}
    {tab==='home'&&<><section className="hero"><div><span className="eyebrow">QUALITY COMMAND CENTER</span><h2>از مکالمه خام تا اقدام اصلاحی، در یک مسیر قابل ممیزی</h2><p>STT محلی، Rule Engine نسخه‌دار، Human Review و گزارش مدیریتی بدون ارسال صوت به Cloud.</p></div><button className="primary xl" onClick={()=>setTab('upload')}><Upload/>ورود مکالمه جدید</button></section>
     <section className="kpis"><article><span>مکالمات</span><b>{fa.format(stats.volume)}</b><small>{fa.format(stats.scored)} دارای امتیاز</small></article><article><span>میانگین کیفیت</span><b>{stats.scored?fa.format(stats.avg):'—'}</b><small>فقط پرونده‌های قابل امتیاز</small></article><article><span>Review باز</span><b>{fa.format(stats.reviewOpen)}</b><small>{fa.format(stats.reviewRate)}٪ از پرونده‌ها</small></article><article className={stats.criticalRate>0?'risk-kpi':''}><span>Critical rate</span><b>{fa.format(stats.criticalRate)}٪</b><small>نیازمند اقدام مدیریتی</small></article></section>
     <section className="dashboard-grid"><article className="panel span2"><div className="panel-title"><div><h3>روند کیفیت</h3><p>میانگین هفتگی؛ بدون داده مصنوعی</p></div><button onClick={()=>setTab('report')}>جزئیات <ChevronLeft/></button></div><Sparkline rows={trend}/></article><article className="panel"><div className="panel-title"><div><h3>توزیع ریسک</h3><p>بر اساس Ruleهای باز و Critical</p></div></div><RiskDonut r={risks}/></article><article className="panel"><div className="panel-title"><div><h3>اولویت‌های Coaching</h3><p>بیشترین Ruleهای ناقص</p></div></div><Pareto rows={failures.slice(0,5)}/></article></section>
    </>}
    {tab==='upload'&&<section className="two-col"><article className="panel upload-panel"><div className="panel-title"><div><span className="eyebrow">INGEST</span><h3>ورودی مکالمات {meta.label}</h3><p>تا ۱۰۰ فایل؛ پردازش ترتیبی برای پایداری RAM/GPU.</p></div><FileAudio/></div><label>نام پیش‌فرض {meta.personLabel}<input value={person} onChange={e=>setPerson(e.target.value)} placeholder={`مثلاً نام ${meta.personLabel}`}/></label><label className="drop"><Upload/><strong>فایل‌ها را انتخاب یا Drag کنید</strong><small>WAV / MP3 / M4A / WebM / FLAC / OGG</small><input type="file" multiple accept="audio/*" onChange={e=>pick(e.target.files)}/></label><div className="buttons"><button className="primary xl" disabled={busy||!rows.length} onClick={run}><Play/>{busy?progress||'در حال پردازش':'شروع پردازش Batch'}</button>{busy&&<button onClick={()=>stop.current=true}><Square/>توقف بعد از فایل جاری</button>}</div><div className="secure-note"><ShieldCheck/><div><b>حریم داده</b><span>Whisper و AI داخل مرورگر اجرا می‌شوند؛ صوت خام Upload نمی‌شود.</span></div></div></article><article className="panel queue-panel"><div className="panel-title"><div><h3>صف پردازش</h3><p>{fa.format(rows.length)} از ۱۰۰ فایل</p></div></div><div className="queue">{rows.map(r=><div className={'queue-row '+r.status} key={r.key}><div className="file-icon"><FileAudio/></div><div className="file-main"><b>{r.file.name}</b><input value={r.personName} placeholder={`نام ${meta.personLabel}`} onChange={e=>patch(r.key,{personName:e.target.value})}/><small>{(r.file.size/1024/1024).toFixed(1)} MB</small></div><span className="state">{r.message}</span>{r.status==='failed'&&<button onClick={()=>manual(r)}>Transcript دستی</button>}</div>)}{!rows.length&&<div className="empty-state"><FileAudio/><b>صف خالی است</b><span>فایل‌های صوتی انتخاب‌شده اینجا نمایش داده می‌شوند.</span></div>}</div></article></section>}
    {tab==='review'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">HUMAN-IN-THE-LOOP</span><h3>صف Review</h3><p>Critical و Evidence ناقص باید قبل از تأیید دیده شوند.</p></div><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جست‌وجوی نام، فایل یا متن…"/></div></div><div className="table responsive-table"><table><thead><tr><th>{meta.personLabel}</th><th>مکالمه</th><th>Conversation</th>{domain==='sampler'&&<th>Workflow</th>}<th>Final</th><th>ریسک</th><th>وضعیت</th><th/></tr></thead><tbody>{reviewRows.map(x=><tr key={x.id}><td><b>{x.personName}</b></td><td>{x.sourceName}</td><td>{x.qc?.conversationScore??'—'}</td>{domain==='sampler'&&<td>{x.qc?.workflowScore??'—'}</td>}<td>{x.qc?.finalScore??'—'}</td><td><span className={'risk '+(x.qc?.risk||'medium')}>{x.qc?.risk||'—'}</span></td><td><span className={x.status==='completed'?'tag good':'tag'}>{x.status==='completed'?'تکمیل':'نیازمند بررسی'}</span></td><td><button className="icon-btn" onClick={()=>{setSelected(x);const e=x.qc?.workflowEvidence||x.reviews?.at(-1)?.workflowEvidence;setWf(e?{nightAttempts:e.nightAttempts??0,twentyMinuteSpacing:e.twentyMinuteSpacing??'unknown',morningRetry:e.morningRetry??'unknown',userAnswered:e.userAnswered??'unknown',finalStatus:e.finalStatus??'unknown',coordinationRecorded:e.coordinationRecorded??'unknown',reviewerNote:''}:emptyWorkflow)}}><Eye/> بررسی</button></td></tr>)}{!reviewRows.length&&<tr><td colSpan={8}><div className="empty compact">پرونده‌ای برای نمایش وجود ندارد.</div></td></tr>}</tbody></table></div></section>}
    {tab==='people'&&<><section className="section-head"><div><span className="eyebrow">PERFORMANCE</span><h2>پرونده عملکرد {meta.label}</h2><p>روند، Critical Failure و Reviewهای باز برای Coaching هدفمند.</p></div></section><section className="people-grid">{profiles.map(x=><article className="person-card" key={x.name}><div className="avatar">{x.name.slice(0,1)}</div><div className="person-top"><div><h3>{x.name}</h3><span>{fa.format(x.calls)} مکالمه</span></div><b className={x.avg!=null&&x.avg<70?'score bad':'score'}>{x.avg==null?'—':fa.format(x.avg)}</b></div><div className="person-stats"><span>Review باز <b>{x.pending}</b></span><span>Critical <b>{x.critical}</b></span></div><small>آخرین فعالیت: {x.last?new Date(x.last).toLocaleString('fa-IR'):'—'}</small></article>)}{!profiles.length&&<div className="empty-state full"><Users/><b>هنوز پرونده‌ای ساخته نشده</b><span>پس از پردازش اولین مکالمه، Profile به‌صورت خودکار ایجاد می‌شود.</span></div>}</section></>}
    {tab==='report'&&<><section className="section-head report-head"><div><span className="eyebrow">EXECUTIVE ANALYTICS</span><h2>گزارش مدیریتی {meta.label}</h2><p>نمای Executive → علت ریشه‌ای → شخص → مکالمه.</p></div><button onClick={csv}><Download/> خروجی CSV</button></section><section className="kpis"><article><span>Volume</span><b>{stats.volume}</b><small>کل مکالمات</small></article><article><span>Quality Avg</span><b>{stats.scored?fa.format(stats.avg):'—'}</b><small>{stats.scored} پرونده قابل امتیاز</small></article><article><span>Open Review</span><b>{stats.reviewOpen}</b><small>{stats.reviewRate}٪</small></article><article><span>Critical</span><b>{stats.criticalRate}٪</b><small>نرخ پرونده بحرانی</small></article></section><section className="dashboard-grid"><article className="panel span2"><div className="panel-title"><div><h3>Quality Trend</h3><p>هشت هفته اخیر</p></div></div><Sparkline rows={trend}/></article><article className="panel"><div className="panel-title"><div><h3>Risk Mix</h3><p>ترکیب ریسک پرونده‌ها</p></div></div><RiskDonut r={risks}/></article><article className="panel span2"><div className="panel-title"><div><h3>Failure Pareto</h3><p>Ruleهایی که بیشترین سهم در Gap کیفیت دارند.</p></div></div><Pareto rows={failures}/></article><article className="panel"><div className="panel-title"><div><h3>مدیریت Coaching</h3><p>افراد با بیشترین Critical Finding</p></div></div><div className="mini-list">{profiles.slice().sort((a,b)=>b.critical-a.critical).slice(0,6).map(x=><div key={x.name}><span>{x.name}</span><b>{x.critical} Critical</b></div>)}</div></article></section><section className="panel"><div className="panel-title"><div><h3>جدول عملکرد</h3><p>Drill-down آماده تا سطح فرد و تماس</p></div></div><div className="table"><table><thead><tr><th>{meta.personLabel}</th><th>تماس</th><th>میانگین</th><th>Review باز</th><th>Critical</th><th>آخرین فعالیت</th></tr></thead><tbody>{profiles.map(x=><tr key={x.name}><td><b>{x.name}</b></td><td>{x.calls}</td><td>{x.avg==null?'—':fa.format(x.avg)}</td><td>{x.pending}</td><td>{x.critical}</td><td>{x.last?new Date(x.last).toLocaleDateString('fa-IR'):'—'}</td></tr>)}</tbody></table></div></section></>}
    {tab==='qc'&&<section className="rule-layout"><article className="panel"><div className="panel-title"><div><span className="eyebrow">VERSIONED SCORECARD</span><h3>Rule Pack {meta.label}</h3><p>{domain==='sampler'?'sampler-conversation-qc-1.0.0':'physician-qc-1.0-candidate'} · Evidence-first</p></div><ShieldCheck/></div><div className="rule-list">{(domain==='sampler'?CONVERSATION_RULES:PHYSICIAN_RULES).map((r:any)=><div className="rule-row" key={r.id}><div><b>{r.id}</b><span>{r.label}</span></div><strong>{r.weight}</strong>{r.critical&&<em>Critical</em>}</div>)}</div></article><article className="panel"><div className="panel-title"><div><h3>حاکمیت امتیاز</h3><p>قواعدی که از Score جعلی جلوگیری می‌کنند.</p></div></div><div className="guard-list"><div><ShieldCheck/><span><b>Evidence اجباری</b>Rule بدون شاهد Pass نمی‌شود.</span></div><div><ShieldCheck/><span><b>Critical Gate</b>Critical باز، Auto Approve را متوقف می‌کند.</span></div><div><ShieldCheck/><span><b>Human Override</b>Override فقط با Note و Audit ثبت می‌شود.</span></div><div><ShieldCheck/><span><b>AI Isolation</b>Copilot محلی هیچ امتیازی را مستقیم تغییر نمی‌دهد.</span></div></div>{domain==='sampler'?<><div className="policybox"><b>Operational Override</b><p>{WORKFLOW_POLICY.currentOperationalOverride}</p></div><div className="warningbox"><b>Policy Conflict</b><p>{WORKFLOW_POLICY.sourceConflict}</p></div></>:<div className="policybox"><b>Physician Candidate Gate</b><p>تا Calibration فارسی پزشکی، Auto-score پزشک همیشه نیازمند Human Review است. Tone و Vitamin D از QC Score جدا هستند.</p></div>}</article></section>}
    {tab==='model'&&<section className="two-col"><article className="panel"><div className="panel-title"><div><span className="eyebrow">ZERO-COST AI</span><h3>Whisper Model Manager</h3><p>Inference محلی؛ بدون API Token یا اشتراک.</p></div><BrainCircuit/></div><label>پروفایل<select value={mode} onChange={async e=>{const m=e.target.value as ModelMode;setModeState(m);setModelMode(m);setModelInfo(await modelStatus(m))}}><option value="auto">Auto · پایدار</option><option value="standard">Standard · Whisper Small</option><option value="quality">High Quality · Large v3 Turbo Candidate</option></select></label><button className="primary" onClick={warm}><RefreshCw/> آماده‌سازی و Cache مدل</button><div className="score-row four"><div><span>Model</span><b>{modelInfo?.plan?.label||'—'}</b></div><div><span>Device</span><b>{modelInfo?.plan?.device||'—'}</b></div><div><span>Threads</span><b>{modelInfo?.hardware?.hardwareConcurrency||'—'}</b></div><div><span>API Cost</span><b>۰</b></div></div><div className="secure-note"><BrainCircuit/><div><b>Local AI Copilot</b><span>Qwen2.5-0.5B داخل مرورگر فقط برای Summary/Coaching استفاده می‌شود و Score را تغییر نمی‌دهد.</span></div></div>{modelInfo?.plan?.validation==='candidate'&&<div className="warningbox">Turbo تا عبور از Gold فارسی Production Winner نیست.</div>}</article><Calibration onRun={calibrate} gold={gold}/></section>}
    {tab==='system'&&<section className="two-col"><article className="panel"><div className="panel-title"><div><h3>Backup & Recovery</h3><p>Vault رمزگذاری‌شده و قابل انتقال.</p></div><Database/></div><div className="stack-actions"><button className="primary" onClick={backup}><Download/> دریافت Backup رمزگذاری‌شده</button><label className="file-action"><Upload/> Restore Backup<input type="file" accept=".json" onChange={e=>restore(e.target.files?.[0]||null)}/></label></div><div className="secure-note"><Lock/><div><b>Local-first</b><span>Passphrase روی دستگاه می‌ماند و Audit نیز داخل Vault رمزگذاری می‌شود.</span></div></div></article><article className="panel"><div className="panel-title"><div><h3>Audit Trail</h3><p>{fa.format(audit.length)} رویداد ثبت‌شده</p></div><ShieldCheck/></div><div className="audit-list">{audit.slice(0,12).map(x=><div key={x.id}><i/><span><b>{x.action}</b><small>{new Date(x.createdAt).toLocaleString('fa-IR')}</small></span></div>)}{!audit.length&&<div className="empty compact">هنوز رویدادی ثبت نشده است.</div>}</div></article></section>}
   </main>
  </section>
  {selected&&<div className="drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="review-drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">{selected.domain==='sampler'?'SAMPLER REVIEW':'PHYSICIAN REVIEW'}</span><h2>{selected.personName}</h2><p>{selected.sourceName}</p></div><button className="icon-only" onClick={()=>setSelected(null)}><X/></button></div><div className="score-row"><div><span>Conversation</span><b>{selected.qc?.conversationScore??'—'}</b></div>{selected.domain==='sampler'&&<div><span>Workflow</span><b>{scoreWorkflow(wf).workflowScore}</b></div>}<div><span>Final</span><b>{selected.domain==='sampler'?(selected.qc?.conversationScore==null?'—':fa.format(selected.qc.conversationScore*.7+scoreWorkflow(wf).workflowScore*.3)):(selected.qc?.conversationScore??'—')}</b></div><div><span>Risk</span><b>{selected.qc?.risk||'—'}</b></div></div>
   <section className="drawer-section"><div className="drawer-title"><h3>Evidence مکالمه</h3><span>{selected.qc?.version}</span></div><div className="evidence-list">{(selected.qc?.findings||[]).map((x:any)=><div className={(x.matched===true||x.status==='pass')?'ev ok':x.status==='partial'?'ev partial':'ev miss'} key={x.ruleId}><div><b>{x.ruleId} · {x.label}</b>{x.critical&&<em>Critical</em>}</div><span>{x.status||((x.matched)?'Pass':'Needs review')} · Confidence {fa.format((x.confidence||0)*100)}%</span>{x.excerpts?.map((e:string,i:number)=><small key={i}>{e}</small>)}</div>)}</div></section>
   {selected.domain==='physician'&&<section className="drawer-section"><div className="drawer-title"><h3>Signals مستقل</h3><span>روی QC Score اثر ندارند</span></div><div className="signal-grid"><div><span>Vitamin D</span><b>{selected.qc?.vitaminD?.mentioned?'مطرح شده':'مطرح نشده'}</b><small>{selected.qc?.vitaminD?.agreement||'unknown'} · {selected.qc?.vitaminD?.prescriptionStatus||'unknown'}</small></div><div><span>Tone</span><b>{selected.qc?.tone?.respect||'unknown'}</b><small>Empathy: {selected.qc?.tone?.empathy||'unknown'}</small></div></div></section>}
   <section className="drawer-section"><details><summary>Transcript کامل</summary><pre>{selected.transcript}</pre></details></section>
   {selected.domain==='sampler'&&<section className="drawer-section workflow-form"><h3>Workflow Evidence</h3><label>وضعیت پاسخ<select value={wf.userAnswered} onChange={e=>setWf({...wf,userAnswered:e.target.value as any})}><option value="unknown">نامشخص</option><option value="yes">پاسخ داده</option><option value="no">عدم پاسخ</option></select></label><label>تعداد تماس شب<select value={wf.nightAttempts} onChange={e=>setWf({...wf,nightAttempts:Number(e.target.value) as any})}><option value="0">۰</option><option value="1">۱</option><option value="2">۲</option><option value="3">۳</option></select></label><label>فاصله ۲۰ دقیقه<select value={wf.twentyMinuteSpacing} onChange={e=>setWf({...wf,twentyMinuteSpacing:e.target.value as any})}><option value="unknown">نامشخص</option><option value="yes">تأیید شده</option><option value="no">رعایت نشده</option></select></label><label>Retry صبح<select value={wf.morningRetry} onChange={e=>setWf({...wf,morningRetry:e.target.value as any})}><option value="unknown">نامشخص</option><option value="yes">انجام شده</option><option value="no">انجام نشده</option><option value="not_applicable">نامرتبط</option></select></label><label>وضعیت نهایی<select value={wf.finalStatus} onChange={e=>setWf({...wf,finalStatus:e.target.value as any})}><option value="unknown">نامشخص</option><option value="confirmed">هماهنگ شد</option><option value="user_declined">عدم تمایل</option><option value="no_answer_cancelled">لغو عدم پاسخ</option><option value="rescheduled">تغییر زمان</option></select></label><label>ثبت در سیستم<select value={wf.coordinationRecorded} onChange={e=>setWf({...wf,coordinationRecorded:e.target.value as any})}><option value="unknown">نامشخص</option><option value="yes">ثبت شده</option><option value="no">ثبت نشده</option></select></label></section>}
   <section className="drawer-section ai-box"><div className="drawer-title"><h3>AI Copilot محلی</h3><span>بدون API / بدون اثر مستقیم روی Score</span></div>{selected.aiInsight?<pre className="ai-result">{selected.aiInsight.summary}</pre>:<p>برای خلاصه‌سازی، تشخیص ریسک و Coaching از مدل محلی استفاده کن.</p>}<button disabled={aiBusy} onClick={aiAssist}><BrainCircuit/>{aiBusy?'در حال تحلیل…':'تحلیل با AI محلی'}</button></section>
   <section className="drawer-section"><label>Evidence / یادداشت Reviewer<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="دلیل تصمیم، Evidence تکمیلی یا اقدام Coaching…"/></label><div className="review-actions"><button onClick={()=>review('referred')}>ارجاع</button>{selected.qc?.criticalFailures?.length>0&&<button className="warn" onClick={()=>review('overridden')}>Override مستند</button>}<button className="primary" onClick={()=>review('approved')}>تأیید Review</button><button className="danger ghost" onClick={async()=>{if(confirm('این پرونده حذف شود؟ Audit حذف باقی می‌ماند.')){await deleteCase(selected.id);setSelected(null);await load()}}}><Trash2/> حذف</button></div></section>
  </aside></div>}
 </div>
}
class RuntimeBoundary extends React.Component<{children:React.ReactNode},{error:string|null}>{constructor(p:any){super(p);this.state={error:null}}static getDerivedStateFromError(e:any){return{error:e?.message||String(e)}}componentDidCatch(e:any,info:any){console.error('KULEPOSHTI_RUNTIME_ERROR',e,info)}render(){if(this.state.error)return<main className="fatal"><section><h1>کوله‌پشتی</h1><h2>Runtime Recovery</h2><p>رابط با یک محدودیت مرورگر مواجه شد. داده Vault حذف نشده است.</p><pre>{this.state.error}</pre><div className="buttons"><button className="primary" onClick={()=>location.reload()}>بارگذاری مجدد</button><button onClick={()=>{try{localStorage.clear()}catch{};location.reload()}}>پاک‌سازی تنظیمات سبک</button></div></section></main>;return this.props.children}}
const root=document.getElementById('root');if(!root)throw new Error('ROOT_ELEMENT_MISSING');createRoot(root).render(<RuntimeBoundary><App/></RuntimeBoundary>);
