export type ModelMode='auto'|'standard'|'quality';
export type HardwareProfile={webgpu:boolean;deviceMemoryGb:number|null;hardwareConcurrency:number;storageQuotaMb:number|null;storageUsageMb:number|null;browser:string};
export type ModelPlan={mode:ModelMode;id:string;label:string;device:'webgpu'|'wasm';dtype:any;reason:string;fallbackId:string|null;authRequired:false;subscriptionRequired:false;license:'MIT'};
export const CATALOG={standard:{id:'onnx-community/whisper-small',label:'Whisper Small · استاندارد'},quality:{id:'onnx-community/whisper-large-v3-turbo',label:'Whisper Large v3 Turbo · کیفیت بالا'}} as const;
function browserName(){const u=navigator.userAgent;if(/Edg\//.test(u))return'Edge';if(/Chrome\//.test(u))return'Chrome';if(/Firefox\//.test(u))return'Firefox';if(/Safari\//.test(u))return'Safari';return'Browser'}
export async function probeHardware():Promise<HardwareProfile>{const n=navigator as Navigator&{deviceMemory?:number;gpu?:unknown};let q:null|number=null,u:null|number=null;try{const e=await navigator.storage?.estimate?.();q=e?.quota?Math.round(e.quota/1048576):null;u=e?.usage?Math.round(e.usage/1048576):null}catch{}return{webgpu:Boolean(n.gpu),deviceMemoryGb:typeof n.deviceMemory==='number'?n.deviceMemory:null,hardwareConcurrency:navigator.hardwareConcurrency||1,storageQuotaMb:q,storageUsageMb:u,browser:browserName()}}
function strong(h:HardwareProfile){const mem=h.deviceMemoryGb==null?h.hardwareConcurrency>=12:h.deviceMemoryGb>=8;return h.webgpu&&mem&&h.hardwareConcurrency>=8}
export function choosePlan(mode:ModelMode,h:HardwareProfile):ModelPlan{if((mode==='quality'||mode==='auto')&&strong(h))return{mode,id:CATALOG.quality.id,label:CATALOG.quality.label,device:'webgpu',dtype:'fp16',reason:mode==='quality'?'کیفیت بالا: سخت‌افزار مناسب است.':'Auto: WebGPU و منابع کافی؛ Turbo انتخاب شد.',fallbackId:CATALOG.standard.id,authRequired:false,subscriptionRequired:false,license:'MIT'};return{mode,id:CATALOG.standard.id,label:CATALOG.standard.label,device:h.webgpu?'webgpu':'wasm',dtype:h.webgpu?'fp16':'q8',reason:mode==='quality'?'Hardware Guard مدل بزرگ را رد کرد؛ Small انتخاب شد.':mode==='standard'?'Standard انتخاب شد.':'Auto: Small برای پایداری انتخاب شد.',fallbackId:null,authRequired:false,subscriptionRequired:false,license:'MIT'}}
export function getMode():ModelMode{const x=localStorage.getItem('kp-model-mode');return x==='quality'||x==='standard'||x==='auto'?x:'auto'}export function setMode(x:ModelMode){localStorage.setItem('kp-model-mode',x)}
export async function requestPersistentStorage(){try{return await navigator.storage?.persist?.()??false}catch{return false}}
