import type{QcDomain}from'./domain';
export type Review={id:string;decision:'approved'|'referred'|'overridden'|'rejected';workflowScore:number|null;conversationScore:number|null;finalScore:number|null;note:string;workflowEvidence?:any;reviewer?:string;createdAt:string};
export type CaseRecord={id:string;domain:QcDomain;personName:string;sourceName:string;audioSha256:string;durationSeconds:number;transcript:string;stt:any;qc:any;status:'needs_review'|'completed';reviews:Review[];aiInsight?:any;createdAt:string;updatedAt:string};
export type AuditEvent={id:string;caseId?:string;domain?:QcDomain;action:string;detail:any;createdAt:string};
const DB='kuleposhti-operational-v1',VER=2,CASES='cases',META='meta',HASH='hashes',AUDIT='audit';let sessionKey:CryptoKey|null=null;
function openDb():Promise<IDBDatabase>{return new Promise((res,rej)=>{if(!('indexedDB'in globalThis)||!globalThis.indexedDB){rej(new Error('IndexedDB در این مرورگر در دسترس نیست یا توسط تنظیمات Privacy مسدود شده است.'));return}let r:IDBOpenDBRequest;try{r=indexedDB.open(DB,VER)}catch{rej(new Error('دسترسی به Storage مرورگر مسدود است.'));return}r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(CASES))d.createObjectStore(CASES,{keyPath:'id'});if(!d.objectStoreNames.contains(META))d.createObjectStore(META);if(!d.objectStoreNames.contains(HASH))d.createObjectStore(HASH);if(!d.objectStoreNames.contains(AUDIT))d.createObjectStore(AUDIT,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function req<T>(r:IDBRequest<T>):Promise<T>{return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const b64=(u:Uint8Array)=>{let s='';for(const x of u)s+=String.fromCharCode(x);return btoa(s)},unb64=(s:string)=>{const x=atob(s),u=new Uint8Array(x.length);for(let i=0;i<x.length;i++)u[i]=x.charCodeAt(i);return u};
async function derive(pass:string,salt:Uint8Array){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:salt as BufferSource,iterations:250000},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function enc(key:CryptoKey,v:any){const iv=crypto.getRandomValues(new Uint8Array(12)),raw=new TextEncoder().encode(JSON.stringify(v)),out=await crypto.subtle.encrypt({name:'AES-GCM',iv:iv as BufferSource},key,raw);return{iv:b64(iv),cipher:b64(new Uint8Array(out))}}
async function dec(key:CryptoKey,v:any){const out=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(v.iv) as BufferSource},key,unb64(v.cipher) as BufferSource);return JSON.parse(new TextDecoder().decode(out))}
async function metaGet(k:string){const d=await openDb(),t=d.transaction(META,'readonly');return req<any>(t.objectStore(META).get(k))}
async function metaPut(k:string,v:any){const d=await openDb(),t=d.transaction(META,'readwrite');t.objectStore(META).put(v,k);await new Promise<void>((a,b)=>{t.oncomplete=()=>a();t.onerror=()=>b(t.error)})}
export async function hasVault(){return Boolean(await metaGet('salt'))}
export async function initVault(pass:string){if(pass.length<12)throw new Error('Passphrase حداقل ۱۲ کاراکتر باشد');const salt=crypto.getRandomValues(new Uint8Array(16)),k=await derive(pass,salt),check=await enc(k,{ok:'kuleposhti-v1'});await metaPut('salt',b64(salt));await metaPut('check',check);sessionKey=k}
export async function unlockVault(pass:string){const s=await metaGet('salt'),check=await metaGet('check');if(!s||!check)throw new Error('Vault ساخته نشده');const k=await derive(pass,unb64(s));const v=await dec(k,check).catch(()=>null);if(v?.ok!=='kuleposhti-v1')throw new Error('Passphrase نادرست است');sessionKey=k}
export function lockVault(){sessionKey=null}
function key(){if(!sessionKey)throw new Error('Vault locked');return sessionKey}
async function audit(action:string,detail:any,caseId?:string,domain?:QcDomain){const d=await openDb(),event:AuditEvent={id:crypto.randomUUID(),caseId,domain,action,detail,createdAt:new Date().toISOString()},encrypted=await enc(key(),event),t=d.transaction(AUDIT,'readwrite');t.objectStore(AUDIT).put({id:event.id,...encrypted});await new Promise<void>((a,b)=>{t.oncomplete=()=>a();t.onerror=()=>b(t.error)})}
export async function listAudit(){const d=await openDb(),t=d.transaction(AUDIT,'readonly'),rows=await req<any[]>(t.objectStore(AUDIT).getAll()),out:AuditEvent[]=[];for(const r of rows)out.push(await dec(key(),r));return out.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
export async function existsHash(hash:string){const d=await openDb(),t=d.transaction(HASH,'readonly');return Boolean(await req(t.objectStore(HASH).get(hash)))}
export async function putCase(c:CaseRecord){const d=await openDb(),encrypted=await enc(key(),c),t=d.transaction([CASES,HASH],'readwrite');t.objectStore(CASES).put({id:c.id,...encrypted});t.objectStore(HASH).put(c.id,c.audioSha256);await new Promise<void>((a,b)=>{t.oncomplete=()=>a();t.onerror=()=>b(t.error)});await audit('case_upsert',{status:c.status,sourceName:c.sourceName},c.id,c.domain)}
export async function listCases(){const d=await openDb(),t=d.transaction(CASES,'readonly'),rows=await req<any[]>(t.objectStore(CASES).getAll()),out:CaseRecord[]=[];for(const r of rows)out.push(await dec(key(),r));return out.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
export async function getCase(id:string){const d=await openDb(),t=d.transaction(CASES,'readonly'),r=await req<any>(t.objectStore(CASES).get(id));return r?await dec(key(),r):null}
export async function deleteCase(id:string){const c=await getCase(id);if(!c)return;await audit('case_deleted',{sourceName:c.sourceName,personName:c.personName},c.id,c.domain);const d=await openDb(),t=d.transaction([CASES,HASH],'readwrite');t.objectStore(CASES).delete(id);t.objectStore(HASH).delete(c.audioSha256);await new Promise<void>((a,b)=>{t.oncomplete=()=>a();t.onerror=()=>b(t.error)})}
export async function saveAiInsight(id:string,insight:any){const c=await getCase(id);if(!c)throw new Error('پرونده پیدا نشد');c.aiInsight=insight;c.updatedAt=new Date().toISOString();await putCase(c);await audit('local_ai_insight',{model:insight?.model||'local'},id,c.domain);return c}
export async function submitReview(id:string,decision:Review['decision'],workflow:number|null,note:string,workflowEvidence?:any){const c=await getCase(id);if(!c)throw new Error('پرونده پیدا نشد');const convRaw=c.qc?.conversationScore;if(convRaw==null)throw new Error('Conversation Score معتبر نیست؛ پرونده باید بررسی دستی شود');const conv=Number(convRaw);let final:number|null=null;
 if(c.domain==='sampler'){if(workflow==null)throw new Error('Workflow Score برای نمونه‌گیر الزامی است');final=Math.round((conv*.7+workflow*.3)*10)/10}else final=Math.round(conv*10)/10;
 const r:Review={id:crypto.randomUUID(),decision,workflowScore:workflow,conversationScore:conv,finalScore:final,note,workflowEvidence,createdAt:new Date().toISOString()};c.reviews=[...(c.reviews||[]),r];c.status=decision==='referred'?'needs_review':'completed';c.updatedAt=new Date().toISOString();c.qc={...c.qc,workflowScore:workflow,finalScore:final,workflowEvidence};await putCase(c);await audit('review_submitted',{decision,workflowScore:workflow,finalScore:final,note},c.id,c.domain);return c}
export async function exportBackup(){const d=await openDb(),tm=d.transaction([META,CASES,HASH,AUDIT],'readonly'),meta:any={};for(const k of['salt','check'])meta[k]=await req(tm.objectStore(META).get(k));const cases=await req<any[]>(tm.objectStore(CASES).getAll()),hashKeys=await req<any[]>(tm.objectStore(HASH).getAllKeys()),hashVals=await Promise.all(hashKeys.map(k=>req(tm.objectStore(HASH).get(k as any)))),auditRows=await req<any[]>(tm.objectStore(AUDIT).getAll());return{version:2,exportedAt:new Date().toISOString(),meta,cases,hashes:hashKeys.map((k,i)=>[k,hashVals[i]]),audit:auditRows}}
export async function importBackup(b:any){if(![1,2].includes(b?.version)||!b.meta?.salt||!Array.isArray(b.cases))throw new Error('Backup نامعتبر');const d=await openDb(),t=d.transaction([META,CASES,HASH,AUDIT],'readwrite');t.objectStore(META).clear();t.objectStore(CASES).clear();t.objectStore(HASH).clear();t.objectStore(AUDIT).clear();t.objectStore(META).put(b.meta.salt,'salt');t.objectStore(META).put(b.meta.check,'check');for(const x of b.cases)t.objectStore(CASES).put(x);for(const[x,y]of b.hashes||[])t.objectStore(HASH).put(y,x);for(const x of b.audit||[])t.objectStore(AUDIT).put(x);await new Promise<void>((a,c)=>{t.oncomplete=()=>a();t.onerror=()=>c(t.error)});sessionKey=null}
